### ISSUE TITLE
Can't read config from environment

### ISSUE THREAD

**Issue by ndarilek** [docker/distribution#1011]
I have the following docker-compose.yml:

```
Registry:
  restart: always
  image: registry:2
  volumes:
  - /home/registry:/var/lib/registry
  environment:
    REGISTRY_STORAGE_S3_ACCESSKEY: xxx
    REGISTRY_STORAGE_S3_SECRETKEY: xxx
    REGISTRY_STORAGE_S3_REGION: us-east-1
    REGISTRY_STORAGE_S3_BUCKET: existing.s3.bucket
    REGISTRY_STORAGE_S3_SECURE: true
    REGISTRY_STORAGE_S3_V4AUTH: true
    REGISTRY_AUTH_HTPASSWD_REALM: Registry
    REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/auth/htpasswd
```

I have verified that these variables appear in the container's environment. The following does not happen:

1. I am not prompted to authenticate with my registry despite the existence of credentials and a valid htpasswd at the specified path.
2. My S3 bucket remains empty.
3. Images are persisted to the local filesystem.
4. I see nothing in the logs indicating communication with S3, attempts to read htpasswd and authenticate requests, etc.

It is almost as if the default config is being used and none of my environment variables are being read. What am I doing wrong here? Seems like I'm following the docs for overriding config via the environment but nothing changes.

Thanks.
