### ISSUE TITLE
Aliyun OSS backend run failed with message "panic: StorageDriver not registered: oss"

### ISSUE THREAD

**Issue by sunadm** [docker/distribution#1015]
docker version
```
Client:
 Version:      1.8.2-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   28220ac
 Built:        Thu Sep  3 19:15:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   28220ac
 Built:        Thu Sep  3 19:15:10 UTC 2015
 OS/Arch:      linux/amd64
```
docker info

```
Containers: 5
Images: 67
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.861 GiB
Name: node13
ID: MB7S:4D37:INQW:GLPL:LJQO:YBL4:2S5Q:2B2R:D7CU:NVR5:MJQW:HDDI
WARNING: No swap limit support
```

docker registry version:  2.1.1

docker command line:
```
docker run -d -p 5000:5000 --restart=always --name registry \
  -e REGISTRY_STORAGE=oss \
  -e REGISTRY_STORAGE_OSS_ACCESSKEYID=xxxx \
  -e REGISTRY_STORAGE_OSS_ACCESSKEYSECRET=xxxxxx \
  -e REGISTRY_STORAGE_OSS_REGION=oss-cn-hangzhou \
  -e REGISTRY_STORAGE_OSS_ENDPOINT=xxxxxx.oss-cn-hangzhou-internal.aliyuncs.com \
  -e REGISTRY_STORAGE_OSS_INTERNAL=true \
  -e REGISTRY_STORAGE_OSS_BUCKET=xxxxxxx \
  -e REGISTRY_STORAGE_OSS_ENCRYPT=false \
  -e REGISTRY_STORAGE_OSS_SECURE=false \
  -e REGISTRY_STORAGE_OSS_CHUNKSIZE=10485760 \
  -e REGISTRY_STORAGE_OSS_ROOTDIRECTORY="" \
  --label SERVICE_5000_NAME="dianjia-distribution" \
  registry:2.1.1
```

docker compose yml:
```
server:
  image: registry:2.1.1
  ports:
    - "5000:5000"
  environment:
    REGISTRY_STORAGE: oss
    REGISTRY_STORAGE_OSS_ACCESSKEYID: xxxxxx
    REGISTRY_STORAGE_OSS_ACCESSKEYSECRET: xxxxxxx
    REGISTRY_STORAGE_OSS_REGION: oss-cn-hangzhou
    REGISTRY_STORAGE_OSS_ENDPOINT: xxxxx.oss-cn-hangzhou-internal.aliyuncs.com
    REGISTRY_STORAGE_OSS_INTERNAL: true
    REGISTRY_STORAGE_OSS_BUCKET: xxxxxx
    REGISTRY_STORAGE_OSS_ENCRYPT: false
    REGISTRY_STORAGE_OSS_SECURE: false
    REGISTRY_STORAGE_OSS_CHUNKSIZE: 10485760
    REGISTRY_STORAGE_OSS_ROOTDIRECTORY: ""
  labels:
    SERVICE_5000_NAME: "dianjia-distribution"
  restart: always
```
