### ISSUE TITLE
Missing REGISTRY_AUTH option in documentation: "Deploying a registry server"

### ISSUE THREAD

**Issue by javicacheiro** [docker/distribution#1031]
The documentation about how to deploy a registry is outdated: https://docs.docker.com/registry/deploying/

The REGISTRY_AUTH=htpaswd option is needed in order to configure the authentication properly.

Without this option you get the following error when trying to login to the local registry:
```
Error response from daemon: no successful auth challenge for https://docker-registry.cesga.es:5000/v2/ - errors: []
```
The correct info should be:
```
docker run -d -p 5000:5000 --restart=always --name registry \
  -v `pwd`/auth:/auth \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e REGISTRY_AUTH=htpasswd \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  registry:2
```
and with docker-compose:
```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /path/data:/var/lib/registry
    - /path/certs:/certs
    - /path/auth:/auth
```
