### ISSUE TITLE
Inconsistent push success with private reg

### ISSUE THREAD

**Issue by djenriquez** [docker/distribution#1081]
Hello,

I am having some intermittent issues when pushing to my private registry. Every now and then, I would see this:

```
bash-3.2$ docker push docker.djsdomain.com/nginxlb
The push refers to a repository [docker.djsdomain.com/gleaner] (len: 3)
93b3ef14f22e: Image already exists 
7e8caf8edd7e: Image already exists 
5bc56a4336e8: Image already exists 
b9e21c8d55d5: Image already exists 
372c3327c04b: Image already exists 
e16543097931: Image already exists 
6559919cc181: Image already exists 
e63ac2612f48: Image already exists 
a37374ad1a4b: Image already exists 
ee509674855c: Image already exists 
017952c77d98: Image already exists 
5352778143e9: Image already exists 
5226672108b5: Image already exists 
cd3cf76a61ee: Image already exists 
491aec45eaf8: Image already exists 
3ac9cfbdf572: Image already exists 
f9bff7d0d06e: Image already exists 
8c7e9b6e3131: Image already exists 
a53219dc4d2f: Image already exists 
5dde53921c3f: Image already exists 
12a77b8bf89a: Image already exists 
ff0618bc0767: Image already exists 
08ecf065655b: Image already exists 
4a5e6db8c069: Image already exists 
2c49f83e0b13: Image already exists 
1.0.0: digest: sha256:86fec1b6a735de6e8966ba02771b3fdefd7868129d7c9d502f86aa23e83cd77b size: 52944
c685b912c80f: Image successfully pushed 
65d93c514dcd: Image successfully pushed 
54ee822e4290: Image successfully pushed 
a599728ed614: Image successfully pushed 
ffdeef56b665: Pushing [==================================================>] 2.556 MB/2.556 MB
unauthorized: access to the requested resource is not authorized
```

I'm seeing this with 1/3 of my pushes.

 I currently have a registry cluster using a common redis cluster as its blobdescriptor cache. Path is distributed with an NGINX RP/LB sitting behind an AWS ELB. NGINX and the ELB do straight TCP passthroughs and all header interaction happens in the registry containers.

All registry containers share a common mounted config.yml, which is below:

```
version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
    environment: comm
storage:
  cache:
    blobdescriptor: redis
  s3:
    region: us-east-1
    bucket: docker.djsdomain.com
auth:
  token:
    realm: "https://dockerauth.djsdomain.com:5001/auth"
    service: "Docker Registry"
    issuer: "djsdomain ACME server"
    rootcertbundle: /etc/docker/ssl/star_djsdomain_com.pem
http:
  addr: :5000
  secret: UEc8BKxfndhpIHbg
  tls:
    certificate: /etc/docker/ssl/star_djsdomain_com.pem
    key: /etc/docker/ssl/star_djsdomain_com.key
redis:
  addr: tcp.djsdomain.com:6379
```

nginx.conf:
```
user  nginx;
worker_processes  2;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  4096;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_requests 1000;
    keepalive_timeout  100;

    server_names_hash_bucket_size   128;

    #gzip  on;

    include /etc/nginx/conf.d/app.conf;
}

stream {
    include /etc/nginx/conf.d/stream.conf;
}
```

stream.conf
```
server {
  listen        5002;
  proxy_pass    docker;
}

upstream docker {
  server        10.170.139.77:32866;
  server        10.170.139.77:32868;
  server        10.170.139.77:32869;
  server        10.170.139.77:32865;
  server        10.170.139.77:32867;
  server        10.170.82.237:32869;
  server        10.170.82.237:32866;
  server        10.170.82.237:32868;
  server        10.170.82.237:32865;
  server        10.170.82.237:32867;
  
}

server {
  listen        5001;
  proxy_pass    dockerauth;
}

upstream dockerauth {
  server        10.170.139.77:32812;
  server        10.170.82.237:32814;
  
}
```

ELB config:
![screen shot 2015-10-07 at 5 03 53 pm](https://cloud.githubusercontent.com/assets/4636740/10354513/794b8970-6d15-11e5-834b-5dc41353fcdb.png)
ELB receives traffic from requests to A Records "docker.djsdomain.com" and "dockerauth.djsdomain.com" and forwards them to three NGINX servers with the identical nginx configuration you see above.

Also, if I scale the registry cluster to one container, I still see the issue.

Any ideas why the registry is behaving inconsistently?
