### ISSUE TITLE
Token authentication error: token signed by untrusted key with ID: "xyz"

### ISSUE THREAD

**Issue by clarktlaugh** [docker/distribution#1143]
I am trying to setup token authentication using the ```cesanta/docker_auth``` token authentication server.  I am constantly getting an error in the log for my registry that indicates the token is signed by an untrusted key:

```
time="2015-10-29T18:55:40Z" level=error msg="token signed by untrusted key with ID: \"OTHY:JAXH:VSAD:VYKK:CYKB:GP4N:P7OL:KDII:2VIS:C3B4:73PC:AOMT\""
```

I believe I have all of the configuration settings correct when running the registry:

```
docker run -d --name docker-registry-v2  \
     --restart=always  \
     -p 5000:5000  \
     -v ${CERTS_DIR}:/ssl:ro  \
     -e REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/linaro.org.crt  \
     -e REGISTRY_HTTP_TLS_KEY=/ssl/linaro.org.key   \
     -e REGISTRY_AUTH=token \
     -e REGISTRY_AUTH_TOKEN_REALM=https://docker-auth.linaro.org:5001/auth \
     -e REGISTRY_AUTH_TOKEN_SERVICE="Docker registry" \
     -e REGISTRY_AUTH_TOKEN_ISSUER="Linaro Registry Auth Service" \
     -e REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/gd_bundle-g2-g1.crt \
     -v ${REGISTRY_DATA_DIR}:/var/lib/registry  \
     registry:2.1.1
```

The HTTP_TLS_CERTIFICATE and HTTP_TLS_KEY are issued by GoDaddy.com, and are working correctly for HTTPS.  I have specified their root certificate bundle in AUTH_TOKEN_ROOTCERTBUNDLE, which is what is supposed to be necessary to validate the token issued correct?

For the authentication server, this is the configuration I am using (https://github.com/cesanta/docker_auth/blob/master/examples/simple.yml).  Referencing the same certificate and private key that I am using for HTTPS:
```
...
server:
  addr: ":5001"
  certificate: "/certs/linaro.org.crt"
  key: "/certs/linaro.org.key"

token:
  issuer: "Linaro Registry Auth Service"  # Must match issuer in the Registry config.
  expiration: 900
...
```

Does AUTH_TOKEN_ROOTCERTBUNDLE need to be something else?
