### ISSUE TITLE
Docker Push Hangs When Registry Uses Rados

### ISSUE THREAD

**Issue by treed** [docker/distribution#1181]
This is sort of a continuation of #1165 ; more details are available there.

I'm having `docker push` hang while pushing a particular layer (the first two push fine), but only when I'm using Rados as storage instead of localstorage.

Running with `docker run -d -p 443:443 --restart=always --name registry -v /etc/ceph:/etc/ceph:ro -v /etc/docker/registry:/etc/docker/registry:ro -v /etc/imvu/certs:/etc/imvu/certs:ro registry:2.2`

Here are the logs from the registry:

http://sprunge.us/EcOb

And the config:

```
version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
    environment: production
storage:
  rados:
    poolname: docker
    username: docker
  cache:
    blobdescriptor: inmemory
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
http:
  addr: 0.0.0.0:443
  secret: [removed]
  tls:
    certificate: /etc/imvu/certs/wildcard.imvu.com.pem
    key: /etc/imvu/certs/wildcard.imvu.com.key
```

And the versions on the client side:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```
