### ISSUE TITLE
config.yml -- Redis - Environment Variable Setting?

### ISSUE THREAD

**Issue by pctj101** [docker/distribution#1188]
in config.yml we set
```
redis:
  addr: localhost:6379
```

However if redis is in another container, it is not possible to determine the host:port ahead of time.

It also is not possible to set the environment variable REGISTRY_variable since that needs to be resolved "again" after launch (and the value is not available to docker run during initial execution).

What's a good way of associating redis from another container with the docker registry:2?

**Comment by RichardScothern** [comment]
@pctj101 : for deploying sets of interacting containers, the recommended method is using [docker compose](https://docs.docker.com/compose/)

**Comment by generalov** [comment]
I use the docker-compose.yml to run a redis and a registry containers together : 
```
cache: 
  image: redis
  restart: always

backend: 
  image: registry:2
  ports: 
    - 127.0.0.l:5000:5000 
  links: 
    - cache 
  volumes: 
    - ./config.yml:/etc/docker/registry/config.yml
    - /srv/docker-registry:/var/lib/registry-cache
  restart: always
```
and I've changed registry config.yml :
```
redis:
  addr: cache:6379
```
where `cache` is the hostname of redis container from docker-compose.yml .
