### ISSUE TITLE
Registry config storage s3 AWS EC2 instance role issue

### ISSUE THREAD

**Issue by ghost** [docker/distribution#1199]
```shell
$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry                2                   dfb4481bd21b        10 days ago         223.4 MB
```
[Documentation](https://github.com/docker/distribution/blob/master/docs/storage-drivers/s3.md) on the s3 storage driver has this explicit Note:
> accesskey: Your aws access key.
> secretkey: Your aws secret key.
>
> Note You can provide empty strings for your access and secret keys if you plan on running the driver on an ec2 instance and will handle authentication with the instance's credentials.

The note leads you to believe you should include YAML keys named accesskey and secretkey and leave them blank if you intend to use an IAM Role to grant s3 access to your instance. However, it fails every time.

```yaml
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        accesskey:
        secretkey:
        region: us-east-1
        bucket: foo.docker.registry
        encrypt: false
        secure: false
        v4auth: false
```

What you have to do is not include the key fields and then things work as expected.

```yaml
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        region: us-east-1
        bucket: foo.docker.registry
        encrypt: false
        secure: false
        v4auth: false
```
I suspect the code is using the blank values from YAML instead of ignoring them.

**Comment by RichardScothern** [comment]
@joecrotty : good observation.  What happens when empty double quotes are used?

**Comment by joecrotty** [comment]
@RichardScothern Empty double quotes worked fine.

```yaml
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        accesskey: ""
        secretkey: ""
        region: us-east-1
        bucket: foo.docker.registry
        encrypt: false
        secure: false
        v4auth: false
```
