### ISSUE TITLE
User not found - Registry 2 & Nginx

### ISSUE THREAD

**Issue by monkeymon** [docker/distribution#1205]
Hi,

I have some issue setting up nginx with docker registry. It seems that docker is unable to get the user and password being used to login. 

I'm following https://docs.docker.com/registry/deploying/ & https://docs.docker.com/registry/nginx/ to set up.

I am able to login via browser using the same user id and password.

My Nginx config is as follow 

```
upstream dockerregistry {
 server localhost:5000;
}
server {
        listen 80;
        listen 443 ssl;

        server_name  docker.mydomain.cc;
        # Make site accessible from http://localhost/
        ssl on;
        ssl_certificate /etc/ssl/certs/domain.bundle.crt;
        ssl_certificate_key /etc/ssl/private/domain.key;
        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;

  # disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;

        proxy_set_header Host $host;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        auth_basic              "Restricted";
        auth_basic_user_file    /etc/nginx/auth/htpasswd;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                proxy_pass http://dockerregistry;
        }
        location /v2/ {
    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
                if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
                        return 404;
                }
                proxy_pass http://localhost:5000;
        }
}
```

My Compose file

```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    SETTINGS_FLAVOR: s3
    AWS_BUCKET: ****
    AWS_REGION: ap-southeast-1
    STORAGE_PATH: /root/registry
    AWS_KEY: *****
    AWS_SECRET: *****
    SEARCH_BACKEND: sqlalchemy
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /home/docker/registry:/var/lib/registry
    - /etc/nginx/auth/:/auth

```

nginx error when i use docker login 
```
2015/11/24 00:02:58 [error] 6217#0: *18 no user/password was provided for basic authentication, client: 128.199.108.188, server: docker.***.**, request: "POST /v1/users/ HTTP/1.1", host: "docker.**.**"
```

My Docker is 1.9 and running ubuntu 14.04
