### ISSUE TITLE
Push to swift registry fails with: error parsing content-length

### ISSUE THREAD

**Issue by dohnto** [docker/distribution#1235]
I am trying to get registry with swift storage driver to work, but I get an error when pushing (when using filesystem storage driver, everything works as excepcted).

#### Docker versions

```bash
 $ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 53
Images: 369
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /www/docker/docker/aufs
 Backing Filesystem: extfs
 Dirs: 477
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.19-zen
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 24
Total Memory: 1.96 GiB
Name: td-jessie
ID: RTOO:4YNE:INVH:TTNN:W5YV:2TYZ:NCCT:7SYD:AZFB:EZKT:ZN6R:7L5B
Username: dohnto
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
```
$ docker exec swift_registry_1 registry -v
registry github.com/docker/distribution v2.2.0
```

#### The command line you used to launch your Registry
I use docker-compose
```yml
registry:
        image: registry:2.2.0
        ports: 
                - 11111:5000
        volumes:
                - ./config.yml:/config.yml
        command: /config.yml
```

config.yml:

```yml
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    swift:
        username: registry_test:registry_test
        password: pass
        authurl: http://swift/auth/v1.0
        container: swift
        insecureskipverify: true
        rootdirectory: /swift/object/name/prefix
http:
    addr: :5000
    secret: "secret"
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

#### Reproducer

```bash
$ docker tag ubuntu localhost:11111/pes
$ docker push localhost:11111/pes
The push refers to a repository [localhost:11111/pes] (len: 1)
e9ae3c220b23: Image already exists 
a6785352b25c: Image already exists 
0998bf8fb9e9: Image push failed 
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax
```

#### Docker daemon log

```
DEBU[0094] Calling POST /v1.21/images/localhost:11111/pes/push 
INFO[0094] POST /v1.21/images/localhost:11111/pes/push?tag= 
DEBU[0094] Trying to push localhost:11111/pes to https://localhost:11111 v2 
DEBU[0094] Error getting v2 registry: Get https://localhost:11111/v2/: tls: oversized record received with length 20527 
DEBU[0094] Trying to push localhost:11111/pes to http://localhost:11111 v2 
DEBU[0094] Checking "" against graph.Repository{"latest":"e9ae3c220b23b699cb5e6914af806219b028c78d5cf6fed8eeca98ffaa8c9b43"} 
DEBU[0094] Pushing repository: pes:latest               
DEBU[0094] Pushing layer: e9ae3c220b23b699cb5e6914af806219b028c78d5cf6fed8eeca98ffaa8c9b43 
DEBU[0094] Pushing layer: a6785352b25c7398637e5ab5a6e989b8371f5dfdf72d9a6cdb00742f262a223e 
DEBU[0094] Pushing layer: 0998bf8fb9e9a5603891f2bfc059555ea8f655c54fe0322f62ea7cb33120b445 
DEBU[0094] Not continuing with error: error parsing content-length: strconv.ParseInt: parsing "": invalid syntax 
```

**Comment by RichardScothern** [comment]
Given that the filesystem driver works ok, there is something up with your swift setup.  It looks like a `Content-Length` headers is not being sent with the response.

How are you running swift?  Can you provide the registry and swift logs?

**Comment by stevvooe** [comment]
@RichardScothern Is this error coming from the [client](https://github.com/docker/distribution/blob/master/registry/client/repository.go#L493)? Is this happening when the client is redirected to swift? Perhaps, we should modify that error message to include url and indicate that the target endpoint doesn't have a content-length header.

**Comment by RichardScothern** [comment]
The error message is misleading - it almost certainly does mean that the header is missing (rather than empty).  I will improve the message.

**Comment by dohnto** [comment]
Thank you for your answers. I dont know where to go next. I dont have really access to the swift. There is nothing in the registry log, and I checked all the files in swift, and they all have Content Length correctly set.

Can you determine, which communication is failing? Is it between the docker client and swift or docker registry and swift or even docker registry and docker client?

**Comment by RichardScothern** [comment]
hi @dohnto : the error is raised by the code in the docker client.  The registry sets the headers correctly and, as you noted, it works fine with non-swift storage backends.  So, the working hypothesis is that the registry is redirecting the client to swift, which is not sending the required header.  Unfortunately, it's difficult to debug without more information.  For instance without the requested registry logs, I cannot validate the above assumption (it would log a redirect being issued).  

Which version of swift are you using?

I'm a little confused about your assertion that all the files in swift have a correct content length.  What exactly do you mean?  If you don't have access to swift, are you able to use a proxy to sniff the headers off the connection?

**Comment by dohnto** [comment]
Ok, I will close this issue. The problem was a varnish cache standing before swift, which sometimes (when requesting HEAD of a file) did not returned content-length.
Thank you all for help.

**Comment by stevvooe** [comment]
@dohnto I think we still have a bug here. Let's track this to get the header parsing fix to give an actionable error message. It likely took some investigation to hunt down the varnish issue.

**Comment by firelyu** [comment]
I face the same issue with ali oss.
config.yml
```
storage:
    cache:
        blobdescriptor: inmemory
    delete:
        enabled: true
    redirect:
        disable: ture
```
```
# docker push myregistry:5000/hello-world:1.0.0
The push refers to a repository [121.43.57.150:5000/hello-world] (len: 1)
0a6ba66e537a: Image push failed 
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax
```

When I enable the redirect, I can push successful.
config.yml
```
storage:
    cache:
        blobdescriptor: inmemory
    delete:
        enabled: true
    redirect:
        disable: false
```
```
# docker push myregistry:5000/hello-world:1.0.0
The push refers to a repository [121.43.57.150:5000/hello-world] (len: 1)
0a6ba66e537a: Pushed 
b901d36b6f2f: Pushed 
1.0.0: digest: sha256:ca706f4f5c1e75033c0d9743b5b015f046ae1b645fe18ad3ef35a79c52652825 size: 2743
```
