### ISSUE TITLE
bug: docker client can't push image to private registry with OSS Internal config

### ISSUE THREAD

**Issue by liuchang23** [docker/distribution#1300]
if i config the storage.redirect.disable=false, I will get following error:
```bash
docker push registry.genedock.com/liuchang0812/python:test                                                                                            The push refers to a repository [registry.genedock.com/liuchang0812/python] (len: 1)
5dcae00f40b3: Image push failed
Head https://genedock-registry-shenzhen.oss-cn-shenzhen-internal.aliyuncs.com/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data?Expires=1451117178&OSSAccessKeyId=juCjgae1f42vSAv4&Signature=%2BmZYvK2yrmez3WDlSF9p2xRegRQ%3D: dial tcp 100.100.0.8:443: i/o timeout
```
otherwise, i will get this error:

```bash
The push refers to a repository [registry.genedock.com/liuchang0812/python] (len: 1)
5dcae00f40b3: Image push failed
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax
```

I have searched this code [storage/blobserver.go](https://github.com/docker/distribution/blob/603ffd58e18a9744679f741f2672dd9aea6babe0/registry/storage/blobserver.go#L37). The switch seems will do nothing if `redirect` is false and urlfor function returns with non-error. 

I'm not good at golang and distribution, does it have a bug here? 

thanks

FIY, my registry config is:

```
storage:
    oss:
        accesskeyid: ****
        accesskeysecret: ***
        region: oss-cn-shenzhen
        internal: true
        bucket: genedock-registry-shenzhen
    delete:
        enabled: false
    cache:
        blobdescriptor: inmemory
    redirect:
        disable: true
```
