### ISSUE TITLE
Docker registry 2.x much slower than 0.x using s3 backend

### ISSUE THREAD

**Issue by NoumanSaleem** [docker/distribution#1318]
Hey all,

After upgrading our registry to 2.x, we are noticing a huge increase in build times, specifically around pushing of the container to the private registry. 

The registry was not migrated from 0.x to 2.0, instead we opted for a clean slate with a new s3 bucket.

I noticed the new registry does not support the old `STORAGE_REDIRECT`, which I believe provided the incredible performance when paired with s3.

Registry Server: Docker version 1.9.1, build a34a1d5
Jenkins Build Server: Docker version 1.9.1, build a34a1d5

Registry Server info:

```bash
> docker exec 72b registry -v
registry github.com/docker/distribution v2.2.1
> docker info
Containers: 4
Images: 41
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.676 GiB
WARNING: No swap limit support

```

New docker-compose for registry 2.x
```yml
registry:
  image: registry:2.2.1
  restart: always
  container_name: registry
  ports:
    - "80:5000"
  environment:
    - REGISTRY_STORAGE=s3 
    - REGISTRY_STORAGE_S3_REGION=us-west-2
    - REGISTRY_STORAGE_S3_BUCKET=
```

Previous docker-compose for registry 0.x
```yml
dockerRegistry:
  image: registry:0.9.1
  ports:
    - "80:5000"
  environment:
    - SETTINGS_FLAVOR=s3
    - AWS_BUCKET=${REGISTRY_BUCKET}
    - STORAGE_PATH=${REGISTRY_STORAGE_PATH}
    - STORAGE_REDIRECT=true
    - SEARCH_BACKEND=sqlalchemy
    - SERVICE_5000_CHECK_HTTP /_ping
    - SERVICE_5000_CHECK_INTERVAL 60s  
```
