### ISSUE TITLE
Docker push gets 502 with S3 as backend

### ISSUE THREAD

**Issue by kevinsimper** [docker/distribution#1339]
I have searched, but I have not found anything in the issues about it.

I am using S3 and it `redirects` the client to upload directly to S3. I am also using Redis as cache, as S3 directly was too slow. 

But sometimes it times out on slow connections and I can't figure out why!

The registry logs does not show anything.
The docker client simply outputs.

```
Received unexpected HTTP status: 502 Bad Gateway
```

It is something about timeout, but I have tried to update the timeout on HAProxy, but it did not help.

If i change the driver from s3 to harddrive, then there is no problem as it is much faster.

Config of HAPROXY

```
global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  log-send-hostname
  maxconn 4096
  pidfile /var/run/haproxy.pid
  user haproxy
  group haproxy
  daemon
  stats socket /var/run/haproxy.stats level admin
  ssl-default-bind-options no-sslv3
  ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DHE-DSS-AES128-SHA:DES-CBC3-SHA
defaults
  balance roundrobin
  log global
  mode http
  option redispatch
  option httplog
  option dontlognull
  option forwardfor
  timeout connect 15000
  timeout client 150000
  timeout server 150000
```

Registry config
v2.2.1

```
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
redis:
  addr: xx
  password: xx
storage:
  cache:
    blobdescriptor: redis
  s3:
    accesskey: xx
    secretkey: xx
    region: xx
    bucket: xx
```

Does S3 have a upload timelimit?
