### ISSUE TITLE
"authentication required" on push after successful login with 2.2

### ISSUE THREAD

**Issue by bweston92** [docker/distribution#1343]
Might be related to #1165 

I've set docker registry:2 up using a docker-compose file and I use nginx to proxy from my domain name to 5000 on the server. 

```
[root@MARLOW:/opt/docker]# cat docker-compose.yml 
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /opt/docker/data:/var/lib/registry
    - /opt/docker/certs:/certs
    - /opt/docker/auth:/auth
```

I run `docker login {hostname}` and it works successfully. How-ever when I try to push I get authentication required.

```
bradley@lindesk22:/var/www$ docker push {hostname}/app-dashboard:latest
The push refers to a repository [{hostname}/app-dashboard] (len: 1)
bdaaa2786dbc: Pushing 1.024 kB
unauthorized: authentication required
```

When I curl with the authentication details it works fine.
