### ISSUE TITLE
Error response from daemon: Missing certificate domain.cert for key domain.key

### ISSUE THREAD

**Issue by aterreno** [docker/distribution#1371]
Hi all, 
I've been hacking my registry for almost 2 days now and no luck finding a solution to this so far. 

I've setup a registry at this address:
`curl -vvvv -i -L https://registry.equalexperts.io:5000/v2/`

The docker compose is pretty straight forward:

```yaml
cache:
  image: redis
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  links:
    - cache
  volumes:
    - /home/ubuntu/data:/var/lib/registry
    - /home/ubuntu/certs:/certs
    - /home/ubuntu/auth:/auth
    - /home/ubuntu/config.yml:/etc/docker/registry/config.yml
frontend:
  image: konradkleine/docker-registry-frontend
  ports:
    - 8081:80
  environment:
    ENV_DOCKER_REGISTRY_HOST: registry
    ENV_DOCKER_REGISTRY_PORT: 5000
```
with the config.yml being:

```yaml
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: staging
storage:
  s3:
    accesskey: <ACCESS_KEY>
    secretkey: <SECRET_KEY>
    region: eu-west-1
    bucket: ee-docker-registry-data
    encrypt: false
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /registry
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
http:
    addr: 0.0.0.0:5000
    host: https://registry.equalexperts.io:5000
    tls:
      certificate: /certs/registry.equalexperts.io.chained.crt
      key: /certs/registry.equalexperts.io.key
    debug:
        addr: localhost:5001
redis:
    addr: localhost:6379
    db: 0
```

I do successfully curl and login to my registry from a docker-machine running on max os 

```bash
docker -v Docker version 1.9.1, build a34a1d5
docker-machine -v Version: 0.5.5, build 02c4254
```

However attempting to push an image causes this error:

`Error response from daemon: Missing certificate registry.equalexperts.io.cert for key registry.equalexperts.io.key`

The whole list of commands is:

```bash
docker run hello-world
docker tag hello-world registry.equalexperts.io:5000/hello-world
docker push registry.equalexperts.io:5000/hello-world
docker tag hello-world registry.equalexperts.io:5000/hello-world
docker push registry.equalexperts.io:5000/hello-world
```

The certificates are created with sslmate, and as you can see in the config.yml I am passing the chained one to the docker registry. 

I really can't see what is wrong with my configuration. 

Thanks in advance, 

toni 

Quick addition (that might help if anybody else is searching for workarounds), amending `sudo vi /var/lib/boot2docker/profile` the docker-machine file by adding: 

`--insecure-registry registry.equalexperts.io:5000`  inside the default: `EXTRA_ARGS='--label provider=virtualbox'` did the trick (you will have to restart the docker daemon `sudo /etc/init.d/docker restart` 

Makes the push work, of course, the whole point of getting a certificate was to have a secure registry, so this will unblock me for now but doesn't seem a reasonable solution.
