### ISSUE TITLE
Webhook notifications not working with SSL endpoints

### ISSUE THREAD

**Issue by h0tbird** [docker/distribution#1463]
Docker version:
```
# docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 00:52:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 00:52:02 2016
 OS/Arch:      linux/amd64
```
Docker registry version: 
```
# registry -v
registry github.com/docker/distribution v2.3.0
```

I am running the setup documented [here](https://github.com/h0tbird/docker-portus/blob/master/README.md). `Portus` is an authorization server using SSL.

The `https://127.0.0.1/v2/token` endpoint seems to work fine but the `https://127.0.0.1/v2/webhooks/events` triggers the following error in the registry logs:

```
WARN[2995] httpSink{https://127.0.0.1/v2/webhooks/events} encountered too many errors, backing off 
ERRO[2996] retryingsink: error writing events: httpSink{https://127.0.0.1/v2/webhooks/events}: error posting: Post https://127.0.0.1/v2/webhooks/events: x509: certificate signed by unknown authority, retrying
```

I suspect the notification code has some bug related to TLS. Or perhaps I have a configuration issue.

This is the registry configuration:
```
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  endpoints:
    - name: portus
      url: https://127.0.0.1/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```
Some environment variables exist:
```
REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
REGISTRY_AUTH_TOKEN_SERVICE=127.0.0.1:5000
REGISTRY_AUTH_TOKEN_ISSUER=127.0.0.1
REGISTRY_HTTP_TLS_KEY=/certs/server-key.pem
REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server-crt.pem
REGISTRY_HTTP_SECRET=secret-goes-here
REGISTRY_AUTH_TOKEN_REALM=https://127.0.0.1/v2/token
REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/server-crt.pem
```
