### ISSUE TITLE
Won't support ceph rados anymore?

### ISSUE THREAD

**Issue by qinghua** [docker/distribution#1541]
Hi, I noticed that there is a [commit](https://github.com/docker/distribution/commit/5967d333425a8dd5d36c5bb456098839654d38af) which removes ceph rados driver in favor of Swift API gateway support.

What's the idea behind that? Does that mean ceph rados will not be supported anymore? We're going to deploy our private registry using rados, shall we change our storage choice?

Thanks!

**Comment by RichardScothern** [comment]
@qinghua :  we removed the ceph driver as the original maintainers were no longer able to contribute to its upkeep.  Ceph can still be used with the Registry using the swift driver and the ceph object gateway swift API.

When Ceph make a release supprting S3 v4 authentication (which has been merged into the Ceph codebase already), the S3 driver and Ceph S3 API can be used.

**Comment by qinghua** [comment]
@RichardScothern Thanks for your response, I'll close this issue.

**Comment by kiwenlau** [comment]
@RichardScothern 

I want to use Ceph S3 API. But I failed, following is the docker registry configuration file:

```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    region: default
    bucket: docker-registry
    accesskey: XC5SVD9ZGQD0D0BG3J0H
    secretkey: uu3oqDZQjBFA22YqcuO4siuxecFVM0yYYHZ6COm4
    regionendpoint: 192.168.59.1:80
    secure: false
http:
    addr: :6000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
threshold: 3
```
