### ISSUE TITLE
s3 write layer not working in v2.4.0-rc.0

### ISSUE THREAD

**Issue by drewrobb** [docker/distribution#1562]
Using 2.3.1 I'm able to push layers to s3 fine. Using 2.4.0-rc.0 however this pushing layers fails. Pulling layers and getting layer information is fine. Failure seems to occur using storage driver s3, s3aws, and s3goamz. I'm relying on IAM roles for s3 access credentials. Some of the s3 requests are succeeding, just not the ones when a write operation is needed.

Error message is: `error resolving upload: s3aws: AccessDenied: Access Denied\n\tstatus code: 403`

I can add more details about my configuration and reproducing this if necessary

**Comment by dliappis** [comment]
@drewrobb confirmed on my side too as per the linked issue. This is unfortunate because `2.4.0-rc` fixes important cloudfront issues with signed URLs.

**Comment by RichardScothern** [comment]
@drewrobb thanks for the report.

A 403 is being returned from S3 on writes for some reason.  Could you post your configuration?

Can you confirm that the error happens with s3goamz as well (you have `s3goamz` as the driver in the config file).

Also, do you have s3 logging enabled?  And if so, is there any reference to this in the logs.

**Comment by drewrobb** [comment]
@RichardScothern correct, I could reproduce with s3goamz and s3 as the driver. My config is this:

```
version: 0.1
log:
    level: debug
    formatter: text
storage:
  s3goamz:
    region: us-east-1
    bucket: my-bucket
    rootdirectory: docker-registry-test
  cache:
    layerinfo: inmemory

```


s3 logging is a good idea. I will add that and update.
