### ISSUE TITLE
S3 driver v4auth false does actually send version 4 Authorization

### ISSUE THREAD

**Issue by fernandodelaiglesia** [docker/distribution#1606]
Hi

I'm testing the image 140a3a1928c9 with a compatible S3 storage and I'm getting errors because this S3 compatible storage does not support AWS signature V4. But if I set v4auth option = false I continue seeing in the PUT (or GET) the Authorization header as:

Authorization:  AWS4-HMAC-SHA256 Credential=ACCESSKEY/20160406/eu-west-1/s3/aws4_request, SignedHeaders=host;range;x-amz-date, Signature=0de4242640d6a0f780c39e09c6a42f51fbaa61a551eed216a02a94357a981d81

I understand that this shoudl be somethig as

Authorization: AWS ACCESSKEY:yvwaJtopLCxHn5565RjwtRW9UsM=

Config.yml file
```
version: 0.1
log:
  level: error
  fields:
    service: registry
storage:
  s3:
    bucket: fimregistry2
    accesskey: ACCESSKEY
    secretkey: SECRETKEY
    region: us-east-1 (I tried some other as eu-west-1, just in case)
    regionendpoint: http://S3ENDPOINT
    secure: false
    v4auth: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
```
Thank you in advance
Best
