### ISSUE TITLE
The notifications endpoint does not supply tag field in event structure!

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#1617]
I are using the notification API to build an index of images pushed for building a search API and Migrating,so the image tag is in need! But my test shows that there is no tag field in event structure! as below:
`{6a5ecdb1-a590-4f8d-afef-c907b1bfa3fd 2016-04-11 16:27:00.558433843 +0800 CST pull {{application/octet-stream %!s(int64=224153958) sha256:c0a04912aa5afc0b4fd4c34390e526d547e67431f6bc122084f1e692dcb7d34e} %!s(int64=224153958) dbyin/busybox  https://registry.com/v2/dbyin/busybox/blobs/sha256:c0a04912aa5afc0b4fd4c34390e526d547e67431f6bc122084f1e692dcb7d34e} {ee16b716-d246-4376-b4cf-6220ec0e605e 10.193.1.158 registry.com HEAD docker/1.11.0-dev go/go1.5.2 git-commit/37a1fad-unsupported kernel/3.10.83-1-tlinux2-0021.tl1 os/linux arch/amd64} {dbyin} {TENCENT64_site:5000 62dbd998-59d9-4ec1-9941-2929fb5f1c1f}}`

And my configuration is that:

```
notifications:
    endpoints:
      - name: alistener
        disabled: false
        url: http://myhost:8086/event
        timeout: 500ms
        threshold: 5
        backoff: 1s
```

urgently!!!
