### ISSUE TITLE
[SWIFT][ceph] error pushing to the registry, unable to parse time error

### ISSUE THREAD

**Issue by gschukin** [docker/distribution#1673]
I'm tring to setup latest release (also tried master) with ceph Firefly as storage backend and swift driver. Unfortuantely i'm facing this error in registry logs with failed push.
```
time="2016-04-26T14:39:46.782197286Z" level=debug msg="swift.Writer(\"/docker/registry/v2/repositories/redis/_uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516/data\", true)" environment=development go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=1e3ec34b-fbb1-4c65-8ec2-29c0bcc22923 http.request.method=PATCH http.request.remoteaddr="172.17.42.1:43162" http.request.uri="/v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry trace.duration=89.284371ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=bfe65d69-86b6-45c2-be44-778c4d6700d9 trace.line=124 vars.name=redis vars.uuid=47066a4f-d75d-4718-954a-aa4b9f0f4516 version=v2.4.0 
time="2016-04-26T14:39:46.782280848Z" level=error msg="error resolving upload: swift: parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"" environment=development go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=1e3ec34b-fbb1-4c65-8ec2-29c0bcc22923 http.request.method=PATCH http.request.remoteaddr="172.17.42.1:43162" http.request.uri="/v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry vars.name=redis vars.uuid=47066a4f-d75d-4718-954a-aa4b9f0f4516 version=v2.4.0 
time="2016-04-26T14:39:46.782363118Z" level=error msg="response completed with error" environment=development err.code=unknown err.detail="swift: parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"" err.message="unknown error" go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=1e3ec34b-fbb1-4c65-8ec2-29c0bcc22923 http.request.method=PATCH http.request.remoteaddr="172.17.42.1:43162" http.request.uri="/v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=180.236063ms http.response.status=500 http.response.written=202 instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry vars.name=redis vars.uuid=47066a4f-d75d-4718-954a-aa4b9f0f4516 version=v2.4.0 
172.17.42.1 - - [26/Apr/2016:14:39:46 +0000] "PATCH /v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9 HTTP/1.1" 500 202 "" "docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))"
time="2016-04-26T14:39:46.786419096Z" level=debug msg="authorizing request" environment=development go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=5a53f9ff-ce45-40cb-aa2f-6e3663e1117b http.request.method=HEAD http.request.remoteaddr="172.17.42.1:43178" http.request.uri="/v2/redis/blobs/sha256:3526e56c913b13dd4173467dac44138d98fca5c50d0dbeff28657112035c89ec" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry vars.digest="sha256:3526e56c913b13dd4173467dac44138d98fca5c50d0dbeff28657112035c89ec" vars.name=redis version=v2.4.0 
```

```
docker version
Client:
 Version:      1.11.1-rc1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   c90c70c
 Built:        Tue Apr 26 04:55:03 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1-rc1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   c90c70c
 Built:        Tue Apr 26 04:55:03 2016
 OS/Arch:      linux/amd64
```
```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.1-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.785 GiB
Name: gleb-virtual-machine
ID: 6LNL:2GXT:LRXG:UG32:ZXAL:WGYR:OZ2B:XIOK:WGJF:AOG2:RH5S:3GFR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

I also tried different versions of Docker but the issue still exists.

Registry config
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
  swift:
    username: REMOVED
    password: REMOVED
    authurl: REMOVED
    tenantid: REMOVED
    insecureskipverify: false
    container: DockerDistribution
    rootdirectory: /registry
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
  redirect:
    disable: false
http:
    addr: :5000
    secret: 530cceaef4af43b989405690f067d7ae
    headers:
        X-Content-Type-Options: [nosniff]
redis:
  addr: 10.16.208.6:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
```
