### ISSUE TITLE
Support GovCloud S3

### ISSUE THREAD

**Issue by RLovelett** [docker/distribution#1712]
When trying to start a container with the following configuration:

```
...
storage:
  s3:
    region: us-gov-west-1
    bucket: bucket-dev
    accesskey: 
    secretkey: 
```

The container fails to start with a "panic" `panic: Invalid region provided: us-gov-west-1`. It would seem that GovCloud is not supported.

Is this expected?

**Comment by RichardScothern** [comment]
The S3 regions supported in the driver match what AWS publish and I do not see us-gov-west-1 as an S3 region.  http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by gschukin** [comment]
@RichardScothern they are defined here https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html

**Comment by RichardScothern** [comment]
Those are endpoints.  Endpoints can be configured separately to regions.  Will those endpoints work with an empty region configured?

**Comment by RLovelett** [comment]
@RichardScothern supplying an empty region with an end point does not work (e.g., `panic: No region parameter provided`).

```
...
storage:
  s3:
    region:
    regionendpoint: s3-website-us-gov-west-1.amazonaws.com 
    bucket: bucket-dev
    accesskey: 
    secretkey: 
```

While I can see your point, that there are no S3 docs that specifically note the GovCloud region name as `us-gov-west-1` there are plenty of docs for other services that indicate it.

For instance, the [RDS docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html) this clearly shows the region being `us-gov-west-1`.

Or the [AWS GovCloud (US) User Guide](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-us-ug.pdf) when talking about ARN:

>  If an ARN requires a region, for the AWS GovCloud (US) Region, the region should be identified as
`us-gov-west-1`.

Point is I think the lack of docs is an indication of the immaturity of GovCloud and the new region. Rather than an indication that the concept is wrong.
