### ISSUE TITLE
Private registry push is very slow

### ISSUE THREAD

**Issue by xflash** [docker/distribution#1756]
Hi Dockers,

I'm just trying to mount a private registry:2 container locally.
the hosting docker is a 
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

The docker registry is running onto a 
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

When I'm trying to tag & push some customized images, ita takes a huge amount of time to upload : 
Nearly 64min to upload a 274MB layer ?!
Here is my docker-compose.yml for the registry part : 
```
registry_data:
  image: registry:2
  command: /bin/true
  container_name: registry_data
registry:
  restart: always
  image: registry:2
  container_name: registry
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /var/lib/registry/certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /var/lib/registry/certs/domain.key
  volumes_from:
    - registry_data
```

Is there something wrong in my configuration ? Or are there some tricks to enhance this uploads ?

Thanks for your help
