### ISSUE TITLE
Garbage collection requires config file to run

### ISSUE THREAD

**Issue by itatabitovski** [docker/distribution#1789]
Running garbage collection requires a configuration file and does not take into consideration the environment variables that work for running the registry.

If this is the docker-compose.yml
```
redis:
    container_name: docker-registry-redis
    image: redis
registry:
    container_name: docker-registry
    environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry/data
    - REGISTRY_HTTP_ADDR=0.0.0.0:5000
    - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis
    - REGISTRY_REDIS_ADDR=redis:6379
    image: registry:2.4
```

This does not work:
```
docker-compose run --rm registry garbage-collect --dry-run 
configuration error: configuration path unspecified

Usage: 
  registry garbage-collect <config> [flags]
Flags:
  -d, --dry-run=false: do everything expect remove the blobs
  -h, --help=false: help for garbage-collect


Additional help topics:

```

**Comment by RichardScothern** [comment]
@itatabitovski  All subcommands require a configuration file (or path to one), and the environment variables override specific sections.  The garbage collect command uses configuration parameters other than the root directory also.

**Comment by itatabitovski** [comment]
@RichardScothern thank you for the information.

I was under the impression that all settings can be configured via environment variables.

Just curious, if loading the configuration works in one way for the main command why load it differently for the subcommands?

**Comment by RichardScothern** [comment]
I'm sorry, I think I misled you: the configuration loading is identical across all subcommands (`registry serve` and `registry garbage-collect`).  They read a config file, then look for environment variables to override specific sections.

In theory all settings can be configured with environment variables, but some are easier than others.  For example, to configure endpoint notifications (which takes an array) would require putting a yaml formatted array in an environment variable.

**Comment by itatabitovski** [comment]
As mentioned in the first [comment](https://github.com/docker/distribution/issues/1789#issue-160143780) the garbage-collect does not work if I run it via docker-compose which contains the relevant environment settings.

Putting those exact settings in a config file make garbage-collect work.
```
cat gc-config.yml
version: 0.1
storage:
  filesystem:
    rootdirectory: /registry/data
  cache:
    blobdescriptor: redis
redis:
  addr: redis:6379

```

If configuration loading is the same and the variables are the same I would expect garbage-collect to work?! This way I have to update the variables in both places (or use config file only).
