### ISSUE TITLE
Cannot push to S3 backed private registry: Connection refused

### ISSUE THREAD

**Issue by tinganho** [docker/distribution#1871]
I was beginning to get this error yesterday, whenever I push:

```
$ docker push my.registry.com/something:1.1

# Logs from client
The push refers to a repository [.....] (len: 1)
7a21803f09b0: Pushing 1.024 kB
Head https://s3.amazonaws.com/REDACTED/registry/docker/registry/v2/blobs/sha256/a3/....
dial tcp 127.0.0.1:443: connection refused

# Logs from registry
registry_1        | time="2016-07-30T04:04:34Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.6.3 http.request.host=REDACTED http.request.id=ff82fd84-77e4-4423-9a1a-57d4cb97855f http.request.method=GET http.request.remoteaddr=118.163.202.115 http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-25-generic os/linux arch/amd64" instance.id=REDACTED version=v2.5.0
registry_1        | 172.17.0.6 - - [30/Jul/2016:04:04:34 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-25-generic os/linux arch/amd64"
registry_1        | time="2016-07-30T04:04:36Z" level=info msg="response completed" go.version=go1.6.3 http.request.host=d.flanity.com http.request.id=REDACTED http.request.method=HEAD http.request.remoteaddr=REDACTED http.request.uri="REDACTED" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-25-generic os/linux arch/amd64" http.response.contenttype="application/octet-stream" http.response.duration=159.07858ms http.response.status=307 http.response.written=0 instance.id=df333fbc-f15e-4770-ada6-0e2b21c8e988 version=v2.5.0
registry_1        | 172.17.0.6 - - [30/Jul/2016:04:04:36 +0000] "HEAD REDACTED HTTP/1.1" 307 0 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-25-generic os/linux arch/amd64"
```

And here is my docker-compose file:
```
registry:
    restart: always
    image: registry:2
    environment:
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        REGISTRY_STORAGE: s3
        REGISTRY_STORAGE_S3_ACCESSKEY: REDACTED
        REGISTRY_STORAGE_S3_SECRETKEY: REDACTED
        REGISTRY_STORAGE_S3_REGION: us-east-1
        REGISTRY_STORAGE_S3_BUCKET: REDACTED
        REGISTRY_STORAGE_S3_ENCRYPT: "true"
        REGISTRY_STORAGE_S3_SECURE: "true"
        REGISTRY_STORAGE_S3_V4AUTH: "true"
        REGISTRY_STORAGE_S3_CHUNKSIZE: 5242880
        REGISTRY_STORAGE_S3_ROOTDIRECTORY: /registry
        SEARCH_BACKEND: sqlalchemy
    volumes:
        - /data:/var/lib/registry
        - /auth/htpasswd:/auth/htpasswd
```
I have verified that I can login to my registry(I've logged out and logged in serveral times). I can also visit the website where the registry is hosted. I have tried to reinstall the registry from scratch. Though I'm still getting this error.
