### ISSUE TITLE
Support configuring registry as a reverse proxy for Notary

### ISSUE THREAD

**Issue by vikstrous** [docker/distribution#1897]
When using a private registry, by default Notary uses the same hostname to connect to Notary as the hostname of the registry. Alternatively the notary client/ docker client can be configured to use a different domain for the Notary server.

To simplify configuration and remove the need for an extra load balancer I would like to be able to configure registry to act as a proxy for Notary.

This would require the following configs:

* URL
* CA
* insecure TLS option

I imagine this looking something like this in the yaml config:

```
notary-proxy:
  url: https://example.com
  ca-path: /place/with/certs/cert.pem
  ca-cert: |
    aaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaa
  insecure-tls: false
```

ca-cert would take precedence over ca-path and insecure-tls would take precedence over both.

I would prefer for a non https option to not be available since notary server itself does not support non-encrypted connections anyway.

What do you guys think?
