### ISSUE TITLE
Issue with unauthorized after login (followup to #1165)

### ISSUE THREAD

**Issue by sblackstone** [docker/distribution#1910]
I just wanted to point out that many people in #1165  were having issues with putting https:// or the port number on their REGISTRY_HTTP_HOST and the ticket was closed because that is an incorrect thing to do..

However, the documentation clearly shows this in the example:

https://docs.docker.com/registry/configuration/

```
http:
  addr: localhost:5000
  prefix: /my/nested/registry/
  host: https://myregistryaddress.org:5000
```

Thanks,
Stephen
