### ISSUE TITLE
Error parsing HTTP response: unexpected end of JSON input: "" when querying registry (v2.5.0)

### ISSUE THREAD

**Issue by a-palchikov** [docker/distribution#1911]
I'm having an issue with both client and server (version v2.5.0).

I'm synchronizing a local registry dump with a remote registry and having a problem with an initial `HEAD` manifest request that is supposed to return a `manifest_unknown` error. It would've returned it in a GET, but the initial HEAD is not supposed to have a body, so the response comes back empty. The client is expecting the error in the response (`HTTP 404`) although it is the one sending `HEAD` in the first place.
Is this a bug or am I missing anything in the configuration?

I have a dead simple config.yml:

```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /ext/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

Also, it used to work fine previously with `v2.2.1` - when the client would make a `GET` initially. I learned support for `HEAD` requests was added in `v2.3.0` so I'm a bit baffled.
