### ISSUE TITLE
feature request - support multiple auth backend 

### ISSUE THREAD

**Issue by SydOps** [docker/distribution#1944]
refer https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md, we set  authentication servers + openldap servers and make it work with high available. 

```
docker daemon |--> (https:443) ELB-1 (http:5000)--> docker-registry 
              |--> (https:443) ELB-2 (http:5001)--> authentication servers --> openldap
```

So in `/etc/docker/registry/config.yml` , we have below setting, 

```
auth:
  token:
    realm: "https://[authentication_server]/auth"
    service: "my.docker.registry"
    issuer: "Acme auth server"
    rootcertbundle: /certs/auth.crt
```

The problem is, our docker-registry is set in AWS, our business (intranet) need access it from  external  DNS (`docker-registry.example.com`) via proxy and all instances running in aws need access via internal DNS (`docker-registry.in.example.com`). 

As same, we set authentication server DNS with two as well: 

External DNS: `docker-authentication.example.com`
Internal DNS:  `docker-authentication.in.example.com`

But I can only put one in auth.token.realm. 

Could we have multiple reamls:

```
auth:
  token:
    realm: "https://docker-authentication.example.com/auth,https://docker-authentication.in.example.com/auth"
```

so both clients from intranet or in aws can access docker-registry server with auth backup supported?

**Comment by 486** [comment]
Hi,

I have a rough solution for this and would love to make PR. But I'd need some official consensus on how this would be configured. 
As you explained, we need a mapping of the name under which the registry was called to a specific realm URL. I.e. a HTTP request to `registry-internal.com` means we want to use `auth-internal.com/auth` or `whatever-auth.net/auth`. So one way could be:

```
auth:
  token:
    realm:
      - name: 'registry-internal.com'
        realm: 'auth-internal.com/auth'
        default: true
      - name: 'registy-external.com'
        realm: 'whatever-auth.net/some_path/auth'

```
To be backwards compatible, if realm contained only a string, the current behavior would apply. `default`could mark one option to be used if none of the names match the request.
One way to match the requests is to use the `Host:` header of the HTTP request. Most of time there would be a reverse proxy in front of the registry so could be modified if necessary. But in the presence of such a proxy you could also look at `X-Forwarded-Host:`. So there are a few details to work out.

Alternative solution: We would specify a HTTP header field that the registry would look at and use its value as the realm. I.e. if a request contained `X-Docker-Registry-Realm: auth-internal.com/auth`, the registry would return this URL in responses. Then you would add this header to the internal and external routes of your reverse proxy. The elegancy of this solution is that you could potentially use any logic your reverse proxy is capable of to determine the URL. Configuration and knowledge of naming would be moved to the reverse proxy. 

I'd be happy to implement either solution, just need an official response on what would be accepted as a PR.

**Comment by SydOps** [comment]
I like this idea: 

```
auth:
  token:
    -  realm: "https://docker-authentication.example.com/auth"
       service: "my.docker.registry"
       issuer: "Acme auth server"
       rootcertbundle: /certs/auth_external.crt
    -  realm: "https://docker-authentication.in.example.com/auth"
       service: "my.docker.registry"
       issuer: "Acme auth server"
       rootcertbundle: /certs/auth_internal.crt
```

So I can assign internal and external certificate as well. But not sure if `issuer` can be same in each.

**Comment by 486** [comment]
That looks OK, but how would the registry know which tuple to apply for an incoming request? I think every tuple needs an additional field containing the registry hostname associated (the `name:` in my config example).

**Comment by 486** [comment]
In my branch, you can configure it like this:

```
auth:
  token:
    multihost:
      "registry-internal.com":
        realm: "https://docker-authentication.in.example.com/auth"
        service: "my.docker.registry"
        issuer: "Acme auth server"
        rootcertbundle: "/certs/auth_internal.crt"
      "registry-external.com":
        realm: "https://docker-authentication.ext.example.com/auth"
        service: "my.docker.registry"
        issuer: "Acme auth server"
        rootcertbundle: "/certs/auth_external.crt"
      "DEFAULT":
        realm: "https://docker-authentication.in.example.com/auth"
        service: "my.docker.registry"
        issuer: "Acme auth server"
        rootcertbundle: "/certs/auth_internal.crt"
```

That means: 

- If the auth is `token` and the key `multihost` is set, all other fields are ignored. Instead, the map is used to associate a host name (sent in the `Host` HTTP header) with a config set. (I've chosen an extra key because otherwise the configuration parsing code has to be changed a good deal.)
- The `DEFAULT` setting is applied if none of the host names matches an incoming request. 
- If no host name matches and `DEFAULT`is not set, the auth handler returns an error (which becomes a `400 Bad Request` response).
- If the `multihost` key is not present, the registry behaves as before.
