### ISSUE TITLE
Upgrade registry from 2.3.1 to 2.5.1; push fails with invalid manifest

### ISSUE THREAD

**Issue by genei09** [docker/distribution#2023]
docker version 1.12.1 on local and remote

pull from 2.5.1 works as expected

push to 2.5.1 generates:

```
time="2016-10-23T04:01:11.999106349Z" level=warning msg="failed to upload schema2 manifest: manifest invalid: manifest invalid - falling back to schema1"
```

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by genei09** [comment]
Observed the same behavior with Registry version 2.4.1
OSx:
```Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```
docker info
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 46
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 135
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 4FOV:G2VK:5L3V:VFOO:7Y5T:GHBA:NEPU:D7W2:4V23:KJFI:SZ57:DOYT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 39
 Goroutines: 65
 System Time: 2016-10-28T23:48:53.2162642Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.1:5000
 localhost:5000
 127.0.0.0/8
```

CentOS Host
docker version
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64
```
docker info
```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 119
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-202:80-262145-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 19.2 GB
 Data Space Total: 107.4 GB
 Data Space Available: 31.32 GB
 Metadata Space Used: 16.86 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.23-31.54.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.862 GiB
Name: qajenkins.windsorcircle.com
ID: 2RYF:U5P7:RXLG:S5LT:WTOM:TKPE:CQ6E:IDEQ:Y7JP:GPTA:GYMA:VD4U
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```
docker exec before upgrade
```
registry github.com/docker/distribution v2.3.1
```
docker exec registry version after upgrade
```
registry github.com/docker/distribution v2.5.1
```

registry started with compose
```
nginx:
  image: "nginx:1.9"
  restart: always
  ports:
    - 443:443
  links:
    - registry:registry
  volumes:
    - /[path]/nginx/:/etc/nginx/conf.d:ro
registry:
  image: registry:2.5.1
  restart: always
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE: s3
    REGISTRY_STORAGE_S3_REGION: [redacted]
    REGISTRY_STORAGE_S3_BUCKET: [redacted]
    STORAGE_PATH: /registry
    REGISTRY_STORAGE_S3_ACCESSKEY: [redacted]
    REGISTRY_STORAGE_S3_SECRETKEY: [redacted]
    REGISTRY_STORAGE_S3_ENCRYPT: 'true'
    REGISTRY_STORAGE_S3_SECURE: 'true'
    REGISTRY_STORAGE_S3_V4AUTH: 'true'
    REGISTRY_STORAGE_S3_CHUNKSIZE: 5242880
    REGISTRY_STORAGE_S3_ROOTDIRECTORY: /[redacted]
    SEARCH_BACKEND: sqlalchemy
```
