### ISSUE TITLE
No support for s3 storage in us-east-2 region (Ohio)

### ISSUE THREAD

**Issue by eranchetz** [docker/distribution#2075]
Running the registry with the following config
```
#config.yml 
....
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: ""
        secretkey: ""
        region: us-east-2
        bucket: example-docker-registry-ohio
```
Results in:
```
panic: Invalid region provided: us-east-2

```
