### ISSUE TITLE
cache mirror of priviate registry

### ISSUE THREAD

**Issue by zhangxuelai** [docker/distribution#2221]
We can run registry as a pull through cache
```
proxy:
  remoteurl: https://registry-1.docker.io
  username: [username]
  password: [password]
```
but the remoteurl must be "registry-1.docker.io"

Is there any way to build a cache for private registry?
