### ISSUE TITLE
Notification endpoint works with registry:2.3, broken in registry:2

### ISSUE THREAD

**Issue by lucidprogrammer** [docker/distribution#2231]
Registry config is as follows
```
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
storage:
  s3:
    accesskey: myaccesskey
    secretkey: mysecretkey
    region: us-east-1
    bucket: mybucket
http:
  addr: :5000

auth:
  htpasswd:
      realm: basic-realm
      path: /auth/htpasswd
http:
  tls:
    certificate: /certs/server.crt
    key: /certs/private.key
notifications:
  endpoints:
    - name: alistener
      disabled: false
      url: http://ip:8080/listener
      headers:
       Bearer:
      timeout: 15000
      threshold: 5
      backoff: 1000
      ignoredmediatypes:
        - application/octet-stream
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

The above when I run with registry:2.3, it works perfectly.

`sudo docker run --name registry --privileged   -v $(pwd)/auth/:/auth/ -v $(pwd)/nginx/certs:/certs:ro -p 443:5000 -v $(pwd)/config.yml:/etc/docker/registry/config.yml registry:2.3`

Endpoint correctly gets the json payload.

However, when I run with registry:2 (which picks up 2.6.0), it fails
`sudo docker run --name registry --privileged   -v $(pwd)/auth/:/auth/ -v $(pwd)/nginx/certs:/certs:ro -p 443:5000 -v $(pwd)/config.yml:/etc/docker/registry/config.yml registry:2`

I get the following error at the registry console
`time="2017-03-29T04:25:07.336845657Z" level=error msg="retryingsink: error writing events: httpSink{http://<ip>:8080/listener}: error posting: Post http://<ip>:8080/listener: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying" 
`
