### ISSUE TITLE
17.06 docker version breaks registry

### ISSUE THREAD

**Issue by alexey-boyko** [docker/distribution#2351]
Docker version 17.06.0-ce, build 02c1d87
Registry: v2.6.2
registry config:
```
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
      blobdescriptor: inmemory
    s3:
      accesskey: {{ accesskey }}
      secretkey: {{ secretkey }}
      region: us-west-2
      bucket: {{bucket}}
      chunksize: 5242880
      v4auth: true
    redirect:
      disable: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
delete:
   enabled: true
```
when upgrade docker form 17.05 to 17.06 registry 2.6.2 doesn't work properly
when i try to push image to registry i got error
```
29660d0e5bb2: Layer already exists 
85782553e37a: Layer already exists 
745f5be9952c: Layer already exists 
error parsing HTTP 408 response body: unexpected end of JSON input: ""
```
then i downgrade docker back to 17.05 all seems ok
tried on 2 different aws instances same error 
registry storage aws s3
