### ISSUE TITLE
After garbage-collection on registry v2.6.2 unexpected EOF and retries on 'docker pull' (even without deleted blobs/images)

### ISSUE THREAD

**Issue by Oleksii-Terekhov** [docker/distribution#2354]
Error like https://github.com/docker/distribution/issues/1939, but disable cache or redirect not solve issue.

docker-compose.yml
```yaml
version: '2'
services:
  registry:
    image: registry:2
    restart: always
    ports:
      - 5005:5000
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./auth:/auth
      - ./registry:/etc/docker/registry
    logging:
      driver: json-file
```
./registry/config.yml
```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  htpasswd:
    realm: 'Registry Realm'
    path: /auth/htpasswd
```
test shell
```sh
echo cleanup registry data
docker-compose down
sudo rm -rf data/docker/
docker-compose up -d

echo remove all local images
docker rmi python:3.5-slim -f
docker rmi python:3.6-slim -f
docker rmi [registry-url]:5005/python:3.5-slim -f
docker rmi [registry-url]:5005/python:3.6-slim -f

echo pull and tag images with shared layers
docker pull python:3.5-slim
docker pull python:3.6-slim
docker tag python:3.5-slim [registry-url]:5005/python:3.5-slim
docker tag python:3.6-slim [registry-url]:5005/python:3.6-slim

echo push image to local registry
docker push [registry-url]:5005/python:3.5-slim

echo test pulling before restart
docker rmi [registry-url]:5005/python:3.5-slim -f
docker rmi python:3.5-slim -f
docker pull [registry-url]:5005/python:3.5-slim

echo restart without GC
docker-compose down
docker-compose up -d

echo test pulling after restart
docker rmi [registry-url]:5005/python:3.5-slim -f
docker rmi python:3.5-slim -f
docker pull [registry-url]:5005/python:3.5-slim

echo restart with GC
docker-compose down
docker-compose run   registry bin/registry garbage-collect /etc/docker/registry/config.yml
docker-compose up -d

echo test pulling after GC
docker rmi [registry-url]:5005/python:3.5-slim -f
docker rmi python:3.5-slim -f
docker pull [registry-url]:5005/python:3.5-slim

echo push+pull after GC
docker push [registry-url]:5005/python:3.6-slim
docker rmi [registry-url]:5005/python:3.6-slim -f
docker rmi python:3.6-slim -f
docker pull [registry-url]:5005/python:3.6-slim
```

Errors on `docker pull` images pushed after GC:
```
3.6-slim: Pulling from python
ad74af05f5a2: Already exists
0a004373a9cb: Already exists
20960344df6d: Pull complete
e72831e2b128: Retrying in 1 second
590171118e9b: Downloading [==================================================>]  1.741MB/1.741MB
unexpected EOF
```

**Comment by Oleksii-Terekhov** [comment]
When I comment `cache` section from config
```yml
storage:
#  cache:
#    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true
```
error on push image after GC
```
700cd4148b03: Pushed
04187aa3408f: Pushed
d6f47645487e: Pushed
361c4b5300b9: Layer already exists
2c40c66f7667: Layer already exists
errors:
manifest blob unknown: blob unknown to registry
manifest blob unknown: blob unknown to registry
```
