### ISSUE TITLE
private registry catalog v2/_catalog old images not removed

### ISSUE THREAD

**Issue by fedya** [docker/distribution#2434]
Hello.
I removed a lot of old images from my private registry
than i run garbage-collector
and now when i do 
curl -Ls GET http://123.45.56.77:5000/v2/_catalog | jq -r '.repositories[]'
i see my removed images, but of course images not available and deleted from filesystem.

Any ideas how to update registry metadata to remove wiped images?

**Comment by zhouhaibing089** [comment]
did you have cache stuffs configured?

**Comment by fedya** [comment]
What you mean?

**Comment by zhouhaibing089** [comment]
I am just guessing, perhaps your cache(redis or in-memory) does not remove those descriptors. would you mind paste your conf here?

**Comment by ipavlushin** [comment]
I have the same issue.
I see all removed images. Which cache options should I use?
My registry conf:
```
version: 0.1
log:
  fields:
    service: registry
  level: info
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
