### ISSUE TITLE
Config of notifications endpoints using environment variables

### ISSUE THREAD

**Issue by janhelges** [docker/distribution#2443]
Is it possible to specify notifications endpoints url using an environment variable?

The motivation for the question is to have all configuration as environment variables. 
I realize that the ...
```
notifications:
  endpoints:
    - name: alistener
      url: https://my.listener.com/event
      timeout: 1s
      .....
```
...represents an yml-list of endpoints, and the syntax...
```
REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=https://host.somedomain.com/webhooks/events
```
...does not represent such a list (as it actually is a scalar value).

However,  it would be very convenient to be able to specify the endpoint-url with info available at container-startup time. For my purpose it would be a nice feature if I could use an environment variable as a _placeholder_ in the config.yml and specify something like...
```
notifications:
  endpoints:
    - name: alistener
      url: ${MY_ENDPOINT_URL}
      timeout: 1s
      .....
```
...and specify...
```
MY_ENDPOINT_URL=https://host.somedomain.com/webhooks/events
```
... at container startup

Best regards
Jan Helge
