### ISSUE TITLE
registry: support docker secrets for S3 credentials

### ISSUE THREAD

**Issue by zarnovican** [docker/distribution#2483]
## Type

Feature request

## Description

It would be nice if Docker Registry would accept filename, where secret value is expected. This IMHO makes sense only for enviroment variable type configuration.

One possible solution would be to look for `REGISTRY_xxx_FILE` every time `REGISTRY_xxx` is read. If the latter is empty `_FILE` would be used.

Example:
```
services:

    registry:
        image: registry:2.6.2
        environment:
            REGISTRY_STORAGE: s3
            REGISTRY_STORAGE_S3_REGION: eu-west-1
            REGISTRY_STORAGE_S3_BUCKET: foo
            REGISTRY_STORAGE_S3_ACCESSKEY: AKIxxxxxxxxxxxxxxxxxx
            REGISTRY_STORAGE_S3_SECRETKEY_FILE: /run/secrets/bar
```
The code would have to recognize both `REGISTRY_STORAGE_S3_SECRETKEY` and `REGISTRY_STORAGE_S3_SECRETKEY_FILE`. One for the actual value (higher priority). The other, for the file containing the value.

I recon, there might be other configuration parameters that would benefit from this feature as well. Not only S3 credentials.
