### ISSUE TITLE
Cannot push to containerized local registry from other networked container - dial tcp: lookup registry: No address associated with hostname

### ISSUE THREAD

**Issue by Ruin0x11** [docker/distribution#2564]
I have a `docker-compose.yml` like this:

```yml
version: '3'
services:
    registry:
      image: registry:2
      restart: always
      volumes:
          - "/var/lib/registry:/var/lib/registry"
      ports:
        - "5000:5000"
    jenkins:
        build: ./blueocean
        depends_on:
            - registry
        expose:
            - "8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```

I want to build containers inside `jenkins` and push them to `registry` as part of the pipeline. However, this is what happens when I try to `docker push` a container from inside the `jenkins` container:

```
$ docker push registry:5000/somecontainer
The push refers to repository [registry:5000/somecontainer]
Get http://registry:5000/v2/: dial tcp: lookup registry: No address associated with hostname
```

I expected this to work since `registry` is still reachable from `jenkins`:

```
$ ping -c4 registry
PING registry (172.18.0.5): 56 data bytes
64 bytes from 172.18.0.5: icmp_seq=0 ttl=64 time=0.105 ms
64 bytes from 172.18.0.5: icmp_seq=1 ttl=64 time=0.095 ms
64 bytes from 172.18.0.5: icmp_seq=2 ttl=64 time=0.068 ms
64 bytes from 172.18.0.5: icmp_seq=3 ttl=64 time=0.068 ms
--- registry ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.068/0.084/0.105/0.000 ms
```

And I can even use the registry API from inside `jenkins`:

```
$ curl registry:5000/v2/_catalog
{"repositories":["myfirstimage"]}
```

The user inside `jenkins` is already part of the `docker` group and can build containers, just not push anything. I tried using the static IP of the host as the registry URL, since the registry is exposed on localhost anyway, and got a different error:

```
$ docker push 192.168.0.100:5000/myimage
The push refers to repository [192.168.0.100:5000/myimage]
Get http://192.168.0.100:5000/v2/: invalid proxy URL port "5000,http:"
invalid proxy URL port "5000,http:"
```

As a workaround I end up tagging the images with `localhost:5000/someimage` instead and manually push them to the registry when the `registry` container is running.
