### ISSUE TITLE
Adding configurable checkers to health package

### ISSUE THREAD

**Issue by diogomonica** [docker/distribution#271]
**Summary**: The [health package](https://github.com/docker/distribution/pull/230) comes with a few pre-configured checkers. At the moment the only way of adding and configuring Checkers is by registering them in your application. Create the ability to add checkers to an application. This would allow check configurations to be shared across different services without code changes.

**Proposed Solution**: Define a configuration structure to be added to the registry's existing yaml configuration, it may look something like the sample below, it may need to be slightly more verbose. As part of the initialization of a registry, use the configuration to start the appropriate checkers. 

```yaml
...
health:
  checkers:
    filechecker: [/path/one/, /path/two/]
    httpchecker: [http://foo.com, http://bar.com]
...
```
