### ISSUE TITLE
Docker Registry with letsencrypt doesn't work.

### ISSUE THREAD

**Issue by demshin** [docker/distribution#2740]
Env:
ubuntu 18.04
docker 18.06.1-ce, build e68fc7a
docker-compose 1.22.0, build f46880fe

My docker-compose.yml:
```
  registry:
  restart: always
  image: registry:latest
  ports:
    - 443:5000
  environment:
    REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE: /cache.letsencrypt
    REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL: myemail@gmail.com
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_LOG_ACCESSLOG_DISABLED: "true"
    REGISTRY_LOG_LEVEL: "error"
    REGISTRY_STORAGE_DELETE_ENABLED: "true"
    REGISTRY_STORAGE: "s3"
    REGISTRY_STORAGE_S3_ACCESSKEY: "accesskey"
    REGISTRY_STORAGE_S3_SECRETKEY: "secretkey"
    REGISTRY_STORAGE_S3_REGION: "us-east-1"
    REGISTRY_STORAGE_S3_BUCKET: "s3bucket-for-docker-images"
    REGISTRY_HTTP_ADDR: "0.0.0.0:443"
    REGISTRY_HTTP_HOST: "https://registry.examle.com"
  volumes:
    - /home/ubuntu/docker-auth:/auth
```
I run `docker-compose up` and get:
`registry_1  | 2018/10/25 06:04:07 [INFO] acme: Registering account for demshin@gmail.com`
and nothing else happens.

When I try connect to registry from my computer:
`docker login registry.examle.com -u login_name`
I get on my computer:
`Error response from daemon: Get https://registry.examle.com/v2/: remote error: tls: internal error`
On server:
```registry_1  | 2018/10/25 06:04:35 [INFO][registry.examle.com] acme: Obtaining bundled SAN certificate
registry_1  | 2018/10/25 06:04:35 [INFO][registry.examle.com] acme: Could not find solver for: tls-alpn-01
registry_1  | 2018/10/25 06:04:35 [INFO][registry.examle.com] acme: Could not find solver for: dns-01
registry_1  | 2018/10/25 06:04:35 [INFO][registry.examle.com] acme: Could not find solver for: http-01
registry_1  | 2018/10/25 06:04:35 http: TLS handshake error from XX.XX.XX.XX:19105: map[registry.examle.com:[registry.examle.com] acme: Could not determine solvers]```
