### ISSUE TITLE
private repository docker push unknown blob error

### ISSUE THREAD

**Issue by TheEdgeOfRage** [docker/distribution#2746]
I have set up a private docker repository together with portus for user management. I can successfully log in using `docker login`, but when I try to push an image it starts and then dies with the error unknown blob. I have so far found two issues on this repo #928 and #2519 neither of witch helped me. I'm running a single instance and have set the http_secret, so that should not be the issue. Here's my docker-compose:

  ```
registry:
    image: registry:latest
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_LOG_LEVEL: debug
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_HTTP_SECRET: REDACTED_SHA512_STRING
      REGISTRY_AUTH_TOKEN_REALM: https://portus.mydomain.com/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.mydomain.com
      REGISTRY_AUTH_TOKEN_ISSUER: portus.mydomain.com
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/fullchain.pem
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://portus.mydomain.com/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - ./storage/registry:/var/lib/registry
      - /etc/letsencrypt/live/mydomain.com/certs:/certs
```

I have set up nginx on my host to proxy connections to registry.mydomain.com to 5000 and when curling /v2/ I get unauthorized as expected.

Let me know if you need anything else.
