### ISSUE TITLE
GCS Storage driver: garbage-collect marks used blobs as deletable

### ISSUE THREAD

**Issue by FabianKramm** [docker/distribution#2872]
## What happens:
When running `docker exec registry bin/registry garbage-collect --dry-run /etc/docker/registry/config.yml` with a registry that uses a gcs storage bucket, still used blobs are marked as eligible for deletion (and are deleted if running without --dry-run).

Command output:
```
/ $ bin/registry garbage-collect --dry-run /etc/docker/registry/config.y
ml
fabian/test

0 blobs marked, 3 blobs eligible for deletion
blob eligible for deletion: sha256:6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0
blob eligible for deletion: sha256:e622815a17be2052df2a16b6a08fa6eef6fdf8cd2ebb31848162fe9446c8c302
blob eligible for deletion: sha256:2f13de3d94e1702dd6e1433850fbee5071cdc5a257e8ac6df314bf9acbd322e7
```

My gcs bucket with still used layers (from tag latest):
![image](https://user-images.githubusercontent.com/10119814/53702420-8d481180-3dbb-11e9-941e-4bb24b62f45c.png)

Config.yaml:
```
version: 0.1
storage:
  delete:
    enabled: true
  gcs:
    bucket: test-registry-2
    keyfile: /gcs/gcs.keyfile
  cache:
    blobdescriptor: inmemory
http:
  addr: :5000
```

## How to reproduce:

1. Create test bucket
2. Push image
3. Run `docker exec registry bin/registry garbage-collect --dry-run /etc/docker/registry/config.yml`
4. See blobs that are still used are marked for deletion
