### ISSUE TITLE
Notification filter not work when ignored media types are empty

### ISSUE THREAD

**Issue by zhangyoufu** [docker/distribution#2916]
`config.yml` excerpt:
```
notifications:
  events:
    includereferences: true
  endpoints:
    - name: test
      url: http://example.com/callback
      ignore:
        actions:
           - pull
```

[`ignore`](https://github.com/docker/distribution/blob/master/docs/configuration.md#ignore) accepts both `mediatypes` and `actions` filtering. `ignoredSink.Write` implemented the filtering as logical *OR*:
https://github.com/docker/distribution/blob/3226863cbcba6dbc2f6c83a37b28126c934af3f8/notifications/sinks.go#L243-L266

However, the configuration above will not work, because `newIgnoredSink` simply returned the underlying sink when `len(ignored) == 0` (`ignored` is a slice of ignored media types):
https://github.com/docker/distribution/blob/3226863cbcba6dbc2f6c83a37b28126c934af3f8/notifications/sinks.go#L221-L224

This behavior is undocumented, and unexpected. I suggest that we should replace `len(ignored) == 0` with `len(ignored) == 0 && len(ignoreActions) == 0`.
