### ISSUE TITLE
Proposal: new config support for whitelisting on manifest mediatype

### ISSUE THREAD

**Issue by jdolitsky** [docker/distribution#2928]
Add support for new section in the config that allows end-users to limit the types of artifacts allowed in the registry.

See suggested new `validation.manifests.filter` section below. Note: the top-level `validation` section is already defined in [the docs](https://docs.docker.com/registry/configuration/).

Example use case - restrict allowed value for a manifest's `config.mediaType` to limit the types of artifacts you'd like to store in a registry:
```yaml
validation:
  enabled: true
  manifests:
    mediaTypes:
      allow:
        - application\/vnd\.cncf\.(helm\.chart|openpolicyagent)\.config\.v1\+json
```

Which would allow only the following artifact types (i.e. Helm charts and Open Policy Agent):
```
application/vnd.cncf.helm.chart.config.v1+json
application/vnd.cncf.openpolicyagent.config.v1+json
```

I'm guessing this is somehow already possible via some custom middleware or shim, but I think it might be good to expand more on manifest filtering features anyway. Let me know if I'm missing something. I'm happy to implement this. Thanks!
