### ISSUE TITLE
Docker registry not pulling from proxy

### ISSUE THREAD

**Issue by wiryonolau** [docker/distribution#2948]
Hi
I'm running a proxy cache registry that will be use by multiple local vm for experiment, it works normally until last month. Suddenly today it broke, always return 404. 

This is config.yml, only add proxy part nothing fancy, I'm not planning to implement any certificate since it is local use
```yml
version: 0.1                                                                                                      
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
```

```bash
docker volume create registry
docker run \
    --rm \
    -d \
    -p 5000:5000 \
    -v registry:/var/lib/registry \
    -v config.yml:/etc/docker/registry/config.yml \
    --name registry \
registry
```

Pulling image from localhost
```bash
docker pull localhost:5000/mariadb:10.4
Error response from daemon: manifest for localhost:5000/mariadb:10.4 not found

# Log file
time="2019-06-20T07:23:48.704764671Z" level=info msg="response completed" go.version=go1.11.2 http.request.host="localhost:5000" http.request.id=ae72f17e-3e53-41b2-af22-a36f2ee52dab http.request.method=GET http.request.remoteaddr="192.168.16.1:43476" http.request.uri="/v2/" http.request.useragent="docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.15.0-52-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration="706.629µs" http.response.status=200 http.response.written=2 
192.168.16.1 - - [20/Jun/2019:07:23:48 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.15.0-52-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \\(linux\\))"
time="2019-06-20T07:23:51.584051546Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="unknown tag=10.4" err.message="manifest unknown" go.version=go1.11.2 http.request.host="localhost:5000" http.request.id=3a6b45aa-89b1-4541-b6b2-a9bf6f5399a7 http.request.method=GET http.request.remoteaddr="192.168.16.1:43480" http.request.uri="/v2/mariadb/manifests/10.4" http.request.useragent="docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.15.0-52-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.877939995s http.response.status=404 http.response.written=94 vars.name=mariadb vars.reference=10.4 
192.168.16.1 - - [20/Jun/2019:07:23:48 +0000] "GET /v2/mariadb/manifests/10.4 HTTP/1.1" 404 94 "" "docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.15.0-52-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \\(linux\\))"
```
