### ISSUE TITLE
Pull-through cache is not working for private registry: Challenge established with upstream

### ISSUE THREAD

**Issue by avarf** [docker/distribution#3081]
We have 2 private docker registry and I want to configure dreg-1 to pull images from dreg-2 if that image doesn't exist on that machine.

I followed the [documentation](https://docs.docker.com/registry/configuration/) to add another remote private docker registry as pull-through and when I launched the dreg-1 there was no error but I am not able to pull an image which JUST exists on dreg-2 via dreg-1 and I get this error:
```
docker pull dreg-1.io/wws/gateway:test_20-01-13
Error response from daemon: manifest for dreg-1.io/wws/gateway:test_20-01-13 not found: manifest unknown: manifest unknown
```
But that image exists on dreg-2:
```
curl https://username:"pass"@dreg-2.io/v2/wws/gateway/tags/list
{"name":"wws/gateway","tags":["test_20-01-13"]}
```

And my dreg-1 config file:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://dreg-2.io
  username: username
  password: pass
```

And the docker-compose that I use for launching the dreg-1:
```
registry:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  volumes:
    - /home/ubuntu/data/docker:/var/lib/registry
    - /home/ubuntu/nginx/config.yml:/etc/docker/registry/config.yml
```

And the logs of dreg-1 when I want to pull an image that just exists on dreg-2:
```
registry_1     | time="2020-01-13T14:00:47Z" level=info msg="Challenge established with upstream : {https  <nil> dreg-2.io /v2/  %!s(bool=false)  } &{{{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} map[https://dreg-2.io:443/v2/:[{basic map[realm:Restricted Content]}]]}" go.version=go1.7.6 http.request.host=dreg-1.io http.request.id=8e2729c7-e74e-4c8f-b7b1-861ff12d6594 http.request.method=GET http.request.remoteaddr=195.207.5.249 http.request.uri="/v2/wws/gateway/manifests/test_20-01-13" http.request.useragent="docker/19.03.5 go/go1.12.12 git-commit/633a0ea838 kernel/4.15.0-72-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \\(linux\\))" instance.id=22d0da77-68a5-4946-be55-25d8e5848ae7 vars.name="wws/gateway" vars.reference="test_20-01-13" version=v2.6.2 
registry_1     | time="2020-01-13T14:00:47Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="unknown tag=test_20-01-13" err.message="manifest unknown" go.version=go1.7.6 http.request.host=dreg-1.io http.request.id=8e2729c7-e74e-4c8f-b7b1-861ff12d6594 http.request.method=GET http.request.remoteaddr=195.207.5.249 http.request.uri="/v2/wws/gateway/manifests/test_20-01-13" http.request.useragent="docker/19.03.5 go/go1.12.12 git-commit/633a0ea838 kernel/4.15.0-72-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.585283ms http.response.status=404 http.response.written=103 instance.id=22d0da77-68a5-4946-be55-25d8e5848ae7 vars.name="wws/gateway" vars.reference="test_20-01-13" version=v2.6.2 
registry_1     | 172.17.0.7 - - [13/Jan/2020:14:00:47 +0000] "GET /v2/wws/gateway/manifests/test_20-01-13 HTTP/1.0" 404 103 "" "docker/19.03.5 go/go1.12.12 git-commit/633a0ea838 kernel/4.15.0-72-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \\(linux\\))"
```
