### ISSUE TITLE
Error when mounting a unionfs mountpoint inside docker container

### ISSUE THREAD

**Issue by goodevilgenius** [docker/distribution#3099]
This is somewhat similar to an issue reported on the docker/for-win repo (https://github.com/docker/for-win/issues/710), but I had this issue on Linux.

I had a folder on my host, which was a unionfs-fuse mountpoint. I wanted to mount this folder into a docker container.

I tried the following:

```shell
unionfs folder1:folder2 union-folder
cd union-folder
# A docker-compose.yml is in the folder
docker-compose up
```

My `docker-compose.yml` contains:

```yaml
version: '3'
services:
  web:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      YII_ENV: debug
      PHP_USER_ID: 1000
```

I get this error:

```
ERROR: for union-folder_web_1  Cannot start service web: error while creating mount source path '/path/to/union-folder': mkdir /path/to/union-folder: file exists
```
