### ISSUE TITLE
storage.redirect.disable=false and nginx proxy_rewrite together cause SignatureDoesNotMatch on docker pull

### ISSUE THREAD

**Issue by Josua-SR** [docker/distribution#3139]
Hi everybody,

I am running a private docker registry with a private minio cluster as storage backend behind an nginx reverse proxy in a private kubernetes cluster. That seems to bring with it quite a few complications, but this issue is about one that I haven't managed to work around yet.

### So what works:
```
          version: 0.1
          storage:
            cache:
              blobdescriptor: inmemory
            redirect:
              disable: true
            s3:
              accesskey: secret
              secretkey: secret
              region: us-west-1
              regionendpoint: http://minio-service.svc:9000/
              secure: false
              v4auth: true
              bucket: docker
              chunksize: 5242880
              rootdirectory: /
            delete:
              enabled: true
          http:
            addr: :80
            host: https://public-registry-url
            headers:
              X-Content-Type-Options: [nosniff]
            secret: secret
```

This configuration above works reasonably well, with http communication inside the kubernets cluster for both docker and minio, and nginx terminating ssl for the outside world.
However it would be much nicer to let docker pull go directly to minio, rather than having the registry proxy all traffic.

So the goal is to set *storage.redirect.disable* to *false*.

### what happens with *storage.redirect.disable=false*

```
docker pull public-registry-url/some/image:latest
latest: Pulling from some/image
89d9c30c1d48: Already exists 
1f1802bc391c: Pulling fs layer 
9d3eb995e676: Pulling fs layer 
e32388fcbe0f: Pulling fs layer 
8a46773e1043: Waiting 
a8b3b40728ae: Waiting 
error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>docker/registry/v2/blobs/sha256/54/5441e8dc7b0c41049912d368b40f8ea18024f3e510d2e6d65488e288d2176bae/data</Key><BucketName>docker</BucketName><Resource>/docker/docker/registry/v2/blobs/sha256/54/5441e8dc7b0c41049912d368b40f8ea18024f3e510d2e6d65488e288d2176bae/data</Resource><RequestId>16020B239C8D5D15</RequestId><HostId>964c83d4-15f6-4a01-a5c3-973902641be0</HostId></Error>"
```

I was able to trace appearance of the error message directly to a feature of the reverse proxy. namely the *proxy_redirect* directive.

I have configured nginx to rewrite redirects to minio, because for obvious reasons the url of the storage backend is different in the outside world than internal to the cluster - in both protocol and domain:

`proxy_redirect http://minio-service.svc:9000/ https://public-minio-url/`

#### without proxy_redirect:

The first thing to ask - is proxy_redirect necessary?

```
error pulling image configuration: Get http://minio-service.sr-infra.svc:9000/docker/docker/registry/v2/blobs/sha256/54/5441e8dc7b0c41049912d368b40f8ea18024f3e510d2e6d65488e288d2176bae/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1533f4c2-9730-49a1-a31f-00121ccba2f0%2F20200402%2Fus-west-1%2Fs3%2Faws4_request&X-Amz-Date=20200402T153327Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=b7ff399411bf8c3fd1e2e58aa5d07942f5074b82daa06b8fd715bdbc7bf7bb72: dial tcp: lookup minio-service.svc on 192.168.2.1:53: no such host
```

Well, clearly it is :(

#### how about using the public url of the storage backend inside the cluster

This works as expected, but causes bandwith issues when pushing images to the registry, since traffic has to go through the reverse proxy to the registry, and then back to the reverse proxy one more time to finally reach the storage backend :(

### Ideas for Solutions?

I am not sure, really. Perhaps not verify the domain name of the storage backend?
