### ISSUE TITLE
Unable to enable image deletion on docker registry v2

### ISSUE THREAD

**Issue by jlegido** [docker/distribution#3163]
First of all many thanks to all the people involved in this project for their time.

Assumption: running the docker container with below environment variable:

```
-e REGISTRY_STORAGE_DELETE_ENABLED=true
```

Will produce below configuration snippet:

```
storage:
  delete:
    enabled: true
```

If at this point I'm mistaken kindly point me to the right documentation and close this issue, otherwise let's go on.

**Steps to reproduce**

```
docker image rm registry:2

docker stop regitry; docker rm regitry

docker run \
  --name regitry \
  -e REGISTRY_STORAGE_DELETE_ENABLED:=true \
  -d registry:2

docker exec -ti regitry cat /etc/docker/registry/config.yml
```

**Expected behaviour**

Display a config file that includes the delete capability on:

```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**Found behaviour**

Display a config file that DOES NOT includes the delete capability on:

```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**Error messages**

None

**Additional information**

* Docker image SHA: 708bc6af7e5e
* Docker version: 19.03.8, build afacb8b7f0
* Operating system: GNU/linux debian bullseye/sid
