### ISSUE TITLE
Docker Push through Nginx Ingress Proxy stuck in "Preparing" state

### ISSUE THREAD

**Issue by DandyDeveloper** [docker/distribution#3330]
This looks very similar to https://github.com/docker/distribution/issues/970, However the recommendation to change the heading in the article described here: https://docs.docker.com/registry/recipes/nginx/ are not plausible in the setup I have (as other services rely on these headers for proxying, but Nginx offers no easy way in the Ingress resource to update these values). 

I've deployed a Docker Registry via the latest helm version (https://github.com/helm/charts/tree/master/stable/docker-registry) instance against a RadosGW S3 bucket and can see the uploads are making it into the bucket.

I've tried numerous different things to enabling TLS on the registry, adding headers and adjusting the Ingress resource. Nothing seems to change the behavior. 

Does anyone have any suggestions on what might be causing this? 

```
2021-01-13 13:42:31         20 docker/registry/v2/repositories/bridge/bridge-guest/_uploads/c6ffe5ee-9cfe-413d-ad64-5cdfad109ceb/startedat
2021-01-13 13:42:33         20 docker/registry/v2/repositories/bridge/bridge/_uploads/4f02a0a5-c34d-462f-bfa1-7946401a8eb9/startedat
2021-01-13 13:42:33         20 docker/registry/v2/repositories/bridge/busybox/_uploads/f9cf4fd7-87fb-45f3-b9b1-8933d0c91b62/startedat
2021-01-13 13:42:30         20 docker/registry/v2/repositories/bridge/matchbox/_uploads/445ed30d-5d9c-45a0-bddb-b940b4c77c68/startedat
```

If we look at the Nginx Ingress, I see the initial GET but the subsequent HEAD fails with a 404, which would likely correlate with the registry log indicating invalid blob:

Nginx:
```
 [13/Jan/2021:04:53:18 +0000] "GET /v2/ HTTP/1.1" 200 2 "-" "docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/5.4.72-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \x5C(linux\x5C))" 263 0.003 [bridge-mirror-bridge-mirror-5000] [] 10.244.10.135:5000 2 0.002 200 b12f1fe8204e8ed4327752004e1cebb4
[13/Jan/2021:04:53:19 +0000] "HEAD /v2/busybox/blobs/sha256:d60bca25ef07e48961711a71bd92e771efdd574b87f3c254f06c0499404c56a1 HTTP/1.1" 404 0 "-" "docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/5.4.72-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \x5C(linux\x5C))" 326 0.005 [bridge-mirror-bridge-mirror-5000] [] 10.244.10.135:5000 0 0.006 404 41858c3d256e4a111241ff1434ddc09f
```

Registry: 
```
[13/Jan/2021:04:53:18 +0000] "GET /v2/ HTTP/1.1" 200 2 "-" "docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/5.4.72-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \x5C(linux\x5C))" 263 0.003 [bridge-mirror-bridge-mirror-5000] [] 10.244.10.135:5000 2 0.002 200 b12f1fe8204e8ed4327752004e1cebb4
[13/Jan/2021:04:53:19 +0000] "HEAD /v2/busybox/blobs/sha256:d60bca25ef07e48961711a71bd92e771efdd574b87f3c254f06c0499404c56a1 HTTP/1.1" 404 0 "-" "docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/5.4.72-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \x5C(linux\x5C))" 326 0.005 [bridge-mirror-bridge-mirror-5000] [] 10.244.10.135:5000 0 0.006 404 41858c3d256e4a111241ff1434ddc09f
```

I have tried enabling `http.relativeurls` and unfortunately this doesn't appear to have changed anything. 

This is the config I'm using: 

```
    config.yml: |-
      health:
        storagedriver:
          enabled: true
          interval: 10s
          threshold: 3
      http:
        addr: :5000
        headers:
          X-Content-Type-Options:
          - nosniff
        relativeurls: true
      log:
        fields:
          service: registry
      storage:
        cache:
          blobdescriptor: inmemory
        s3:
          bucket: docker-registry
          encrypt: false
          region: us-east-1
          regionEndpoint: http://BucketEndpoint
          secure: false
      version: 0.1
```

My ingress resource looks like this: 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "false" <- This true makes no difference
  name: mirror
  namespace: mirror
spec:
  rules:
  - host: external-registry-address
    http:
      paths:
      - backend:
          serviceName: bridge-mirror
          servicePort: 5000
        path: /
  tls:
  - hosts:
    - external-registry-address
    secretName: tls
```

If I upload via HTTP directly to the registry, the upload is successful. It's only with the proxy. I suspect it's these header that is causing the issue. 

Ingress Proxy Config:
```
                        proxy_set_header X-Request-ID           $req_id;
                        proxy_set_header X-Real-IP              $remote_addr;

                        proxy_set_header X-Forwarded-For        $remote_addr;

                        proxy_set_header X-Forwarded-Host       $best_http_host;
                        proxy_set_header X-Forwarded-Port       $pass_port;
                        proxy_set_header X-Forwarded-Proto      $pass_access_scheme;
```

But without adjusting the config map, which would break other working ingress resources. I'm not sure what to do...
