### ISSUE TITLE
pull on a secure local registry uses http and says "malformed HTTP"

### ISSUE THREAD

**Issue by Shaker1978** [docker/distribution#3336]
Hello,
I am using Docker Desktop 3.1.0 on a Windows Server 2019 1809 (based on Hyper-V), out of the box, fresh installation. I set up a local registry using docker-compose and parameters like these:
```
image: registry:2
    ports:
    - 5000:5000
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_HTTP_TLS_CERTIFICATE: /cert/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /cert/privkey.pem
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./cert:/cert
      - ./data:/data
```
From a remote machine I can "docker login server:5000", and pushing an image also worked**!** All this is using https as desired!

Now locally on the same server I'd like to pull this image from the registry calling:
`docker pull localhost:5000/image:latest`
which shows me, that pull is using http instead of https:
"Error response from daemon: Get http://localhost:5000/v2/: net/http: HTTP/1.x transport connection broken: malformed HTTP response"

Why is pull not using https like login and push? What else am I doing wrong?
