### ISSUE TITLE
.s3/credentials

### ISSUE THREAD

**Issue by sinneduy** [docker/distribution#550]
Every time I try to bring up distribution using docker-compose, I get the following error:

```
time="2015-05-21T23:31:11.029778825Z" level=debug msg="using \"text\" logging formatter"
distribution_1 | panic: No valid AWS authentication found: open /root/.aws/credentials: no such file or directory
distribution_1 |
distribution_1 | goroutine 1 [running]:
distribution_1 | github.com/docker/distribution/registry/handlers.NewApp(0x7fb46d08cc70, 0xc2080a4d50, 0xc20802b9c0, 0x3, 0xc20802b9f8, 0x5, 0xc20802ba28, 0x4, 0xc2080a4780, 0xa63670, ...)
distribution_1 | 	/go/src/github.com/docker/distribution/registry/handlers/app.go:81 +0x5eb
distribution_1 | main.main()
distribution_1 | 	/go/src/github.com/docker/distribution/cmd/registry/main.go:63 +0x44e
distribution_1 |
distribution_1 | goroutine 6 [syscall]:
distribution_1 | os/signal.loop()
distribution_1 | 	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
distribution_1 | created by os/signal.init·1
distribution_1 | 	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
distribution_1 |
distribution_1 | goroutine 17 [syscall, locked to thread]:
distribution_1 | runtime.goexit()
distribution_1 | 	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
```
However, I have the key and secret specified in my config
```
version: 0.1
log:
    level: debug
    formatter: text
    fields:
        service: registry
        environment: prod
storage:
    s3:
        access_key: <redacted>
        secret_key: <redacted
        bucket: docker-pixlee
        region: "us-west-1"
        encrypt: true
        secure: true
        rootdirectory: /srv/docker
        v4auth: true
        chunksize: 5242880
    cache:
        blobdescriptor: redis
    maintenance:
        uploadpurging:
            enabled: true
            age: 168h
            interval: 24h
            dryrun: false
redis:
    addr: redis:6379
    password: <redacted>
    db: 0
    dialtimeout: 10ms
    readtimeout: 10ms
    writetimeout: 10ms
    pool:
        maxidle: 16
        maxactive: 64
        idletimeout: 300
```

I find it very strange that it doesn't use the credentials specified in my config.yml.
Is it required that a credential file is used in the .s3 folder?  And if so, what format should it take?

I couldn't find any documentation around .s3/credentials, apologies in advance if it exists somewhere
