### ISSUE TITLE
storage maintenance not documented

### ISSUE THREAD

**Issue by DarkDirk** [docker/distribution#588]
Hi,
I can't find any documentation for the maintenance configuration setting. Is there none?
```
storage:
    [...]
    maintenance:
        uploadpurging:
            enabled: false
```
