### ISSUE TITLE
Registry on EC2 + S3 occasional Timeouts on docker push

### ISSUE THREAD

**Issue by jwhitcraft** [docker/distribution#707]
Hello,

I'm running v2.0.1 of the registry on a c4.2xl ubuntu ami with docker 1.7.0 and a few times a day when I do a docker push from another ec2 machine in the same VPC, i get a timeout error

```
Error pushing to registry: Head https://s3.amazonaws.com/my-docker-registry/docker/registry/v2/blobs/sha256/35/35fa464854b0bad3cb48d920d30159251ec3164067e07768eab876b62bd26d33/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<left out>%2F20150717%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20150717T005149Z&X-Amz-Expires=1200&X-Amz-Signature=<left out>&X-Amz-SignedHeaders=host: read tcp 54.231.244.8:443: connection timed out
```

The last few lines of the registry log are

```
registry_1  | time="2015-07-17T00:56:31.335673369Z" level=info msg="s3.GetContent(\"/docker/registry/v2/repositories/test/ult-7.7.0.0beta2/_layers/sha256/35fa464854b0bad3cb48d920d30159251ec3164067e07768eab876b62bd26d33/link\")" trace.duration=550.107376ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=709dc503-b0d5-4bfa-a231-53ab24f4042c trace.line=55
registry_1  | time="2015-07-17T00:56:31.960985034Z" level=info msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/35/35fa464854b0bad3cb48d920d30159251ec3164067e07768eab876b62bd26d33/data\")" trace.duration=625.210967ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=a03e7077-a9a8-4e56-ba98-fa2e9f415b05 trace.line=111
registry_1  | time="2015-07-17T00:56:32.597828653Z" level=info msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/35/35fa464854b0bad3cb48d920d30159251ec3164067e07768eab876b62bd26d33/data\")" trace.duration=636.753926ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=7329e5c1-3555-4483-90d4-dd5fee5f660c trace.line=111
```

Here is the docker-compose.yml file that i used to start up the registry server

```yml
redis:
  ports:
  - 6379/tcp
  image: redis
registry:
  ports:
  - 443:5000/tcp
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/my_cert.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry.test.net.key
    REGISTRY_STORAGE_CACHE_LAYERINFO: redis
    REGISTRY_REDIS_ADDR: redis:6379
    REGISTRY_STORAGE: s3
    REGISTRY_STORAGE_S3_ACCESSKEY: <omitted>
    REGISTRY_STORAGE_S3_BUCKET: my-docker-registry
    REGISTRY_STORAGE_S3_REGION: us-east-1
    REGISTRY_STORAGE_S3_SECRETKEY:  <omitted>
    REGISTRY_STORAGE_S3_V4AUTH: 'true'
    REGISTRY_STORAGE_S3_CHUNKSIZE: 5242880
  image: registry:2.0.1
  links:
    redis: redis
  volumes:
  - /etc/certs:/certs
```
