### ISSUE TITLE
Push to swift storage fails to upload manifest with a 404

### ISSUE THREAD

**Issue by lynxnot** [docker/distribution#757]
Hello,

i have tested the brand new Openstack Swift storage driver (#493) against our Ceph Swift cluster, and images are failing to upload with a 404 on the manifest file. 

The storage configuration used is the following : 

```
storage:
    cache:
        blobdescriptor: inmemory
    swift:
        username: ticloud
        password: <THE_PASS>
        authurl: http://172.16.1.5/v2.0
        tenant: ticloud
        insecureskipverify: true
        region: chgva-01
        container: docker-registry
        rootdirectory: 
    maintenance:
        uploadpurging:
            enabled: false
```

The operation for the test :
```
docker tag golang:1.4 localhost:443/ticloud/golang:1.4
docker push localhost:443/ticloud/golang:1.4
```

The error logs :

```
time="2015-07-27T08:25:32.244845786Z" level=error msg="An error occured" err.code="BLOB_UNKNOWN" err.detail=sha256:4d2e9ae40c411dd421f35dd20c133152bed21f8f9b903ba265a5d77c69a79edc err.message="blob unknown to registry" http.request.host="localhost:443" http.request.id=3b3244d5-62bd-432e-9200-9dc000df6f1c http.request.method=PUT http.request.remoteaddr="172.17.42.1:59009" http.request.uri="/v2/ticloud/golang/manifests/1.4" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-58-generic os/linux arch/amd64" vars.name="ticloud/golang" vars.reference=1.4 
time="2015-07-27T08:25:32.245177622Z" level=info msg="response completed" http.request.host="localhost:443" http.request.id=3b3244d5-62bd-432e-9200-9dc000df6f1c http.request.method=PUT http.request.remoteaddr="172.17.42.1:59009" http.request.uri="/v2/ticloud/golang/manifests/1.4" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-58-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=139.517898ms http.response.status=404 http.response.written=2173 
172.17.42.1 - - [27/Jul/2015:08:25:32 +0000] "PUT /v2/ticloud/golang/manifests/1.4 HTTP/1.1" 404 2173 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-58-generic os/linux arch/amd64"
```

All previous layers of the image seems to upload fine. The error is preceded by numerous BLOB_UNKNOWN errors. The full trace it's [here](http://pastebin.com/MMLyntTW)

If needed the listing of the swift container after this operation has been uploaded [here](http://pastebin.com/KF5W810m)

I will keep the infrastructure as is, so let me know if i can help more, just bear in mind im not a go dev :)
