### ISSUE TITLE
Deployment Not Working Fully

### ISSUE THREAD

**Issue by spencerbeggs** [docker/distribution#765]
I am struggling to configure a registry. I am using Docker Compose to build an Nginx proxy, the Docker registry and a Redis cache, Here's my configuration YML:

```yml
redis:
  image: redis
registry:
  restart: always
  image: registry:2.0.1
  ports:
    - "127.0.0.1:5000:5000"
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
    REGISTRY_HTTP_TLS_KEY: /certs/key.key
    REGISTRY_STORAGE: s3
    REGISTRY_STORAGE_S3_ACCESSKEY: REDACTED
    REGISTRY_STORAGE_S3_SECRETKEY: REDACTED
    REGISTRY_STORAGE_S3_REGION: us-east-1
    REGISTRY_STORAGE_S3_BUCKET: REDACTED
    REGISTRY_STORAGE_S3_ENCRYPT: true
    REGISTRY_STORAGE_S3_SECURE: true
    REGISTRY_STORAGE_S3_V4AUTH: true
  volumes:
    - /root/data/certs:/certs
    - /root/data/registry/data:/var/lib/registry
  links:
    - redis
nginx:
  restart: always
  image: nginx
  ports:
    - 443:443
    - 80:80
  volumes:
    - /root/data/nginx/auth:/etc/nginx/auth
    - /root/data/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /root/data/nginx/html:/var/www/html
    - /root/data/certs:/etc/nginx/certs
  links:
    - registry:registry
```

Here's my nginx.conf:

```nginx
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    gzip on;
    gzip_http_version 1.0;
    gzip_proxied any;
    gzip_min_length 500;
    gzip_disable "MSIE [1-6]\.";
    gzip_types text/plain text/xml text/css text/comma-separated-values text/javascript application/x-javascript application/atom+xml;

    # List of application servers
    upstream docker-registry {
        server registry:5000;
    }

    # Registry
    server {
       listen         80;
       server_name    registry.example.com;
       return         301 https://$server_name$request_uri;
    }

    server {
        # Running port
        listen 443;
        server_name registry.example.com;
        ssl on;
        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.key;
        ssl_trusted_certificate /etc/nginx/certs/trusted.pem;
        ssl_ciphers 'AES256+EECDH:AES256+EDH::!EECDH+aRSA+RC4:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS';
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_session_cache shared:SSL:10m;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security max-age=31536000;
        add_header X-Frame-Options DENY;
        client_max_body_size 0;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization "";

        location / {
            proxy_pass https://docker-registry/;
        }
    }
}
```

So, after I run `docker-compose up` the servers come up. I can run the following commands and see the changes end up on S3:

```
docker pull nginx && docker tag nginx registry.example.com/spencer/nginx
docker push registry.example.com/spencer/nginx
```

I can pull the image back with:

```
docker pull registry.example.com/spencer/nginx
```

When I visit https://registry.example.com/v2 I get a 200 and a response of:

```
{}
```

But I can't seem to list out most of the other endpoints. For example, when I hit `https://registry.example.com/v2/spencer/nginx` I get a 404. Same for `https://registry.example.com/v2/_catalog`. 

Here is the response from the server:

```
registry_1 | time="2015-07-27T21:23:07.896092462Z" level=info msg="response completed" environment=development http.request.host=registry.example.com http.request.id=8df28d0a-da5b-40fd-a592-a7b875c4bb17 http.request.method=GET http.request.remoteaddr=96.239.107.171 http.request.uri="/v2/spencer/nginx" http.request.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" http.response.contenttype="text/plain; charset=utf-8" http.response.duration="337.905µs" http.response.status=404 http.response.written=19 instance.id=88d28a04-06de-47a5-b429-de38c5290b40 service=registry version=v2.0.1
registry_1 | 172.17.2.86 - - [27/Jul/2015:21:23:07 +0000] "GET /v2/spencer/nginx HTTP/1.0" 404 19 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36"
nginx_1    | 96.239.107.171 - - [27/Jul/2015:21:23:07 +0000] "GET /v2/spencer/nginx HTTP/1.1" 404 19 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36"
```

I can, however, get a JSON response from `https://registry.example.com/v2/spencer/nginx/manifests/latest` showing an error, so I don't think my nginx configuration is the cause of it.

I would appreciate it if someone could point me in the right direction.
