### ISSUE TITLE
[2.0.1] panic: Get : 301 response missing Location header

### ISSUE THREAD

**Issue by shin-** [docker/distribution#854]
Logs for the distribution container: https://gist.github.com/shin-/e78f7b8430e9e0dc51aa
Configuration YAML:

``` yaml
version: "0.1"
log:
  level: debug
storage:
  s3:
    accesskey: REDACTED
    bucket: dtr-1.3-rc0
    region: us-east-1
    secretkey: REDACTED
auth:
  token:
    issuer: dtr-test.net
    realm: https://dtr-test.net/auth/token
    rootcertbundle: /auth/certs/token_roots.pem
    service: dtr-test.net
http:
  addr: :5000
notifications:
  endpoints:
  - name: audit-logs
    disabled: false
    url: http://admin_server/events/
    headers:
      X-Registry-Events:
      - "true"
    timeout: "0"
    threshold: 0
    backoff: "0"
```

@dmp42 if I can provide more info, let me know.
