### ISSUE TITLE
Cannot connect to debug on 5001

### ISSUE THREAD

**Issue by olibob** [docker/distribution#891]
Hi all,

I have an issue connecting to port 5001 (debug).

Here is my config.yml

```
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
    environment: development
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    debug:
        addr: localhost:5001
```

And my docker-compose.yml file

```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
    - 5001:5001
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_AUTH: htpasswd
  volumes:
    - /reg:/var/lib/registry
    - /root/certs:/certs
    - /root/auth:/auth
    - /root/config:/etc/docker/registry:ro
```

From the registry logs

```
time="2015-08-18T08:46:52.547530278Z" level=info msg="debug server listening localhost:5001"
```

On the host

```
[root@reg-01 ~]# netstat -tapen  | grep 500
tcp6       0      0 :::5000                 :::*                    LISTEN      0          68240      6977/docker-proxy
tcp6       0      0 :::5001                 :::*                    LISTEN      0          69625      6966/docker-proxy
```

The registry uses a self signed certificate (trusted at OS level) and basic htpasswd auth. I can work without any issues with the registry (push/pull/curl commands). But I can't get anything on 5001.

```
[root@reg-01 ~]# curl https://bob:bob2015@myreg.net:5000/v2/_catalog
{"repositories":["busybox","httpd","ubuntu"]}
[root@reg-01 ~]#
```

But

```
[root@reg-01 ~]# curl localhost:5001
curl: (56) Recv failure: Connection reset by peer
[root@reg-01 ~]#
``` 

Could you please let me know what I'm doing wrong?
