### ISSUE TITLE
S3 & IAM role credentials

### ISSUE THREAD

**Issue by djenriquez** [docker/distribution#968]
Hello,

I'm having issues loading the registry config with a blank `accesskey` and blank `secretkey`.

I'm running docker with:
```
docker run \
-d --name registry \
-v "/home/ubuntu/config.yml:/etc/docker/registry/config.yml" \
-p "5000:5000" \
registry:2
```

With the config file:

```
version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
    environment: dev
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey:
    secretkey:
    region: us-west-2
    bucket: my-bucket-name
http:
  addr: localhost:5050
  secret: no
```

I get the log:
```
panic: The AWS Access Key Id you provided does not exist in our records.
```

Documentation says it should use the IAM role attached to the EC2 instance. I verified the instance has access to the bucket by downloading the aws cli and running an `aws s3 cp` command, which succeeded.

This IAM role has full access to S3 and the bucket gives full access to this role.

I found issue #701 but it seems @tiadobatima ended up getting it to work by working around the problem.

How does one get registry to use the IAM role attached to the EC2 instance?
