### ISSUE TITLE
S3 driver uses wrong path for auth check.

### ISSUE THREAD

**Issue by nakedible-p** [docker/distribution#980]
I see in the code for the S3 driver that an initial auth check is made like this:

```
if _, err := bucket.List(strings.TrimRight(params.RootDirectory, "/"), "", "", 1); err != nil {
```
https://github.com/docker/distribution/blob/b0e94fb154789f87f0c794b5e51192548821fed3/registry/storage/driver/s3/s3.go#L224

This means that if I have specified the bucket as `testing` and root directory as `foobar` or (`foobar/`), the distribution makes a List call for the path `s3://testing/foobar`. However, since the List call in Amazon S3 is a simple prefix match, this will also return paths of the style `s3://testing/foobarbaz`. This means that coupled with a bucket policy of for example:

```
    - Effect: Allow
      Action: [ 's3:ListBucket' ]
      Resource: [ 'arn:aws:s3:::testing' ]
      Condition:
        StringLike:
          s3:prefix: ['foobar/*']
```

...causes the access check to fail as `foobar` does not match the pattern `foobar/`. S3 buckets do not behave as unix directories, so this is easy to get wrong there.

The correct fix is to always add a final slash to the "root directory" if it does not already have it, instead of stripping the slash.
